package contractsv1_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/ghassan-ai-projects/agentic-stream/internal/canonicaljson"
	"github.com/ghassan-ai-projects/agentic-stream/internal/contractsv1"
)

// The committed conformance fixtures under conformance/v1/ are the cross-repo
// contract surface: the Streams Simulator device emulator, the edge gateway,
// and the firmware copy these bytes and test their wire compatibility against
// them. This file is the generator and the drift guard in one.
//
// To regenerate after an intentional contract change:
//
//	AGENTIC_STREAM_UPDATE_CONFORMANCE=1 go test ./internal/contractsv1/ -run Conformance
//
// A drift between conformance.go and the committed files fails the build, so a
// schema/example change can never silently diverge from what consumers copy.

const (
	conformanceDir = "conformance/v1"
	updateEnv      = "AGENTIC_STREAM_UPDATE_CONFORMANCE"
)

func canonicalFixture(t *testing.T, doc map[string]any) []byte {
	t.Helper()
	encoded, err := canonicaljson.Marshal(doc)
	if err != nil {
		t.Fatalf("canonical marshal: %v", err)
	}
	return append(encoded, '\n')
}

// wantFixture compares a committed fixture to the freshly generated bytes, or
// (re)writes it under the update env. It returns nothing; failures are fatal.
func wantFixture(t *testing.T, relPath string, generated []byte) {
	t.Helper()
	path := filepath.Join(conformanceDir, relPath)
	if os.Getenv(updateEnv) == "1" {
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatalf("mkdir %s: %v", filepath.Dir(path), err)
		}
		if err := os.WriteFile(path, generated, 0o644); err != nil {
			t.Fatalf("write fixture %s: %v", path, err)
		}
		return
	}
	committed, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read committed fixture %s: %v (regenerate with %s=1)", path, err, updateEnv)
	}
	if string(committed) != string(generated) {
		t.Fatalf("fixture %s is stale; regenerate with %s=1 go test ./internal/contractsv1/", path, updateEnv)
	}
}

func TestConformanceValidFramesValidateAndMatchFixtures(t *testing.T) {
	for _, messageType := range contractsv1.ConformanceValidMessageTypes() {
		messageType := messageType
		t.Run(messageType, func(t *testing.T) {
			doc := contractsv1.ConformanceValidFrame(messageType)
			schema, ok := contractsv1.SchemaForMessageType(messageType)
			if !ok {
				t.Fatalf("no schema for message_type %q", messageType)
			}
			if err := contractsv1.Validate(schema, doc); err != nil {
				t.Fatalf("valid %s frame must validate: %v", messageType, err)
			}
			wantFixture(t, "valid/"+messageType+".json", canonicalFixture(t, doc))
		})
	}
}

func TestConformanceInvalidFramesFailClosedAndMatchFixtures(t *testing.T) {
	seen := map[string]bool{}
	for _, frame := range contractsv1.ConformanceInvalidFrames() {
		frame := frame
		if seen[frame.Name] {
			t.Fatalf("duplicate invalid frame name %q", frame.Name)
		}
		seen[frame.Name] = true
		t.Run(frame.Name, func(t *testing.T) {
			if err := contractsv1.Validate(frame.Schema, frame.Doc); err == nil {
				t.Fatalf("invalid frame %q must fail closed, but validated", frame.Name)
			}
			// Invalid frames are marshaled directly (they cannot pass the codec),
			// so consumers get a byte-exact example of what to reject.
			wantFixture(t, "invalid/"+frame.Name+".json", canonicalFixture(t, frame.Doc))
		})
	}
}
