package storage

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"
)

// ErrRuntimeOwnerBusy means another runtime currently owns the database lease.
var ErrRuntimeOwnerBusy = errors.New("runtime owner lease is held by another process")

// RuntimeOwner manages the singleton lease that fences live runtime
// processes. The owner epoch is opaque and must be generated by the runtime
// process, never by a worker.
type RuntimeOwner struct {
	DB         *DB
	Lease      time.Duration
	Now        func() time.Time
	InstanceID string
}

// Claim acquires or renews the singleton lease for epoch. A valid lease held
// by another epoch is rejected transactionally.
func (o *RuntimeOwner) Claim(ctx context.Context, epoch string) error {
	if o == nil || o.DB == nil || epoch == "" || o.InstanceID == "" {
		return fmt.Errorf("runtime owner is not configured")
	}
	now := o.now()
	leaseUntil := formatRuntimeTime(now.Add(o.leaseDuration()))
	nowText := formatRuntimeTime(now)
	err := o.DB.WithTx(ctx, func(tx *sql.Tx) error {
		_, err := tx.ExecContext(ctx, `
			INSERT INTO runtime_owner (
				singleton_id, owner_epoch, owner_instance, acquired_at,
				heartbeat_at, lease_until
			) VALUES (1, ?, ?, ?, ?, ?)
			ON CONFLICT(singleton_id) DO UPDATE SET
				owner_epoch = excluded.owner_epoch,
				owner_instance = excluded.owner_instance,
				acquired_at = CASE
					WHEN runtime_owner.owner_epoch = excluded.owner_epoch
						AND runtime_owner.owner_instance = excluded.owner_instance
						THEN runtime_owner.acquired_at
					ELSE excluded.acquired_at
				END,
				heartbeat_at = excluded.heartbeat_at,
				lease_until = excluded.lease_until
			WHERE (runtime_owner.owner_epoch = excluded.owner_epoch
				AND runtime_owner.owner_instance = excluded.owner_instance)
				OR (runtime_owner.owner_epoch <> excluded.owner_epoch
					AND runtime_owner.lease_until <= excluded.heartbeat_at)`,
			epoch, o.InstanceID, nowText, nowText, leaseUntil,
		)
		if err != nil {
			return fmt.Errorf("claim runtime owner: %w", err)
		}
		var currentEpoch, currentInstance string
		if err := tx.QueryRowContext(ctx,
			"SELECT owner_epoch, owner_instance FROM runtime_owner WHERE singleton_id = 1",
		).Scan(&currentEpoch, &currentInstance); err != nil {
			return fmt.Errorf("read runtime owner after claim: %w", err)
		}
		if currentEpoch != epoch || currentInstance != o.InstanceID {
			return ErrRuntimeOwnerBusy
		}
		return nil
	})
	if err != nil {
		return err
	}
	return nil
}

// Renew extends the lease only when this epoch still owns it and has not
// already expired. A zero-row update means ownership was lost.
func (o *RuntimeOwner) Renew(ctx context.Context, epoch string) error {
	if o == nil || o.DB == nil || epoch == "" {
		return fmt.Errorf("runtime owner is not configured")
	}
	now := o.now()
	result, err := o.DB.ExecContext(ctx, `
		UPDATE runtime_owner
		SET heartbeat_at = ?, lease_until = ?
		WHERE singleton_id = 1 AND owner_epoch = ? AND owner_instance = ? AND lease_until > ?`,
		formatRuntimeTime(now), formatRuntimeTime(now.Add(o.leaseDuration())), epoch, o.InstanceID, formatRuntimeTime(now),
	)
	if err != nil {
		return fmt.Errorf("renew runtime owner: %w", err)
	}
	if count, err := result.RowsAffected(); err != nil {
		return fmt.Errorf("count renewed runtime owners: %w", err)
	} else if count != 1 {
		return ErrRuntimeOwnerBusy
	}
	return nil
}

// Release clears the singleton lease only for the owning epoch.
func (o *RuntimeOwner) Release(ctx context.Context, epoch string) error {
	if o == nil || o.DB == nil || epoch == "" {
		return fmt.Errorf("runtime owner is not configured")
	}
	now := o.now()
	result, err := o.DB.ExecContext(ctx, `
		UPDATE runtime_owner SET heartbeat_at = ?, lease_until = ?
		WHERE singleton_id = 1 AND owner_epoch = ? AND owner_instance = ?`,
		formatRuntimeTime(now), formatRuntimeTime(now), epoch, o.InstanceID)
	if err != nil {
		return fmt.Errorf("release runtime owner: %w", err)
	}
	if count, err := result.RowsAffected(); err != nil {
		return fmt.Errorf("count released runtime owners: %w", err)
	} else if count != 1 {
		return ErrRuntimeOwnerBusy
	}
	return nil
}

// Assert verifies that epoch currently owns an unexpired lease inside tx.
// Callers use this as the write-fencing predicate for runtime-owned state.
func (o *RuntimeOwner) Assert(ctx context.Context, tx *sql.Tx, epoch string) error {
	if o == nil || tx == nil || epoch == "" {
		return fmt.Errorf("runtime owner is not configured")
	}
	var currentEpoch string
	if err := tx.QueryRowContext(ctx, `
		SELECT owner_epoch FROM runtime_owner
		WHERE singleton_id = 1 AND owner_epoch = ? AND owner_instance = ? AND lease_until > ?`,
		epoch, o.InstanceID, formatRuntimeTime(o.now()),
	).Scan(&currentEpoch); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return ErrRuntimeOwnerBusy
		}
		return fmt.Errorf("assert runtime owner: %w", err)
	}
	return nil
}

func (o *RuntimeOwner) now() time.Time {
	if o.Now != nil {
		return o.Now().UTC()
	}
	return time.Now().UTC()
}

func (o *RuntimeOwner) leaseDuration() time.Duration {
	if o.Lease > 0 {
		return o.Lease
	}
	return time.Minute
}

func formatRuntimeTime(value time.Time) string {
	return value.UTC().Format(time.RFC3339Nano)
}
