package control

import (
	"context"
	"database/sql"
	"time"

	"github.com/ghassan-ai-projects/agentic-stream/internal/control/internal/app"
	"github.com/ghassan-ai-projects/agentic-stream/internal/control/internal/store"
	"github.com/ghassan-ai-projects/agentic-stream/internal/sources"
	"github.com/ghassan-ai-projects/agentic-stream/internal/storage"
)

// RuntimeOwner manages the singleton lease that fences live runtime processes.
// The owner epoch is opaque and must be generated by the runtime process, never
// by a worker. An unconfigured owner (no database, epoch or instance) refuses
// every operation.
type RuntimeOwner struct {
	DB         *storage.DB
	Lease      time.Duration
	Now        func() time.Time
	InstanceID string
}

func (o *RuntimeOwner) session() *app.Owner {
	if o == nil {
		return nil
	}
	return &app.Owner{Store: store.New(o.DB), Instance: o.InstanceID, Lease: o.Lease, Now: sources.NowFunc(o.Now)}
}

// Claim acquires or renews the singleton lease for epoch. A valid lease held
// by another epoch is rejected transactionally.
func (o *RuntimeOwner) Claim(ctx context.Context, epoch string) error {
	return app.Claim(ctx, o.session(), epoch)
}

// ClaimAndRecover acquires the singleton lease and runs recover in the same
// SQLite transaction. If recovery fails, ownership is not committed.
func (o *RuntimeOwner) ClaimAndRecover(ctx context.Context, epoch string, recover func(*sql.Tx, time.Time) error) error {
	return app.ClaimAndRecover(ctx, o.session(), epoch, recover)
}

// Renew extends the lease only when this epoch still owns it and has not
// already expired. A zero-row update means ownership was lost.
func (o *RuntimeOwner) Renew(ctx context.Context, epoch string) error {
	return app.Renew(ctx, o.session(), epoch)
}

// Release clears the singleton lease only for the owning epoch.
func (o *RuntimeOwner) Release(ctx context.Context, epoch string) error {
	return app.Release(ctx, o.session(), epoch)
}

// Assert verifies that epoch currently owns an unexpired lease inside tx.
// Callers use this as the write-fencing predicate for runtime-owned state.
func (o *RuntimeOwner) Assert(ctx context.Context, tx *sql.Tx, epoch string) error {
	return app.Assert(ctx, o.session(), store.Join(tx), epoch)
}
