package control

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"

	"github.com/ghassan-ai-projects/agentic-stream/internal/storage"
)

// ErrRuntimeOwnerBusy means another runtime currently owns the database lease.
var ErrRuntimeOwnerBusy = errors.New("runtime owner lease is held by another process")

// RuntimeOwner manages the singleton lease that fences live runtime
// processes. The owner epoch is opaque and must be generated by the runtime
// process, never by a worker.
type RuntimeOwner struct {
	DB         *storage.DB
	Lease      time.Duration
	Now        func() time.Time
	InstanceID string
}

// Claim acquires or renews the singleton lease for epoch. A valid lease held
// by another epoch is rejected transactionally.
func (o *RuntimeOwner) Claim(ctx context.Context, epoch string) error {
	return o.ClaimAndRecover(ctx, epoch, nil)
}

// ClaimAndRecover acquires the singleton lease and runs recover in the same
// SQLite transaction. If recovery fails, ownership is not committed.
func (o *RuntimeOwner) ClaimAndRecover(ctx context.Context, epoch string, recover func(*sql.Tx, time.Time) error) error {
	if o == nil || o.DB == nil || epoch == "" || o.InstanceID == "" {
		return fmt.Errorf("runtime owner is not configured")
	}
	now := o.now()
	err := o.DB.WithTx(ctx, func(tx *sql.Tx) error {
		return o.claimAndRecoverTx(ctx, tx, epoch, now, recover)
	})
	if err != nil {
		return fmt.Errorf("%w", err)
	}
	return nil
}

func (o *RuntimeOwner) claimTx(ctx context.Context, tx *sql.Tx, epoch string, now time.Time) error {
	if err := o.writeOwnerLease(ctx, tx, epoch, now); err != nil {
		return err
	}
	return o.assertRecordedOwner(ctx, tx, epoch)
}

func (o *RuntimeOwner) writeOwnerLease(ctx context.Context, tx *sql.Tx, epoch string, now time.Time) error {
	leaseUntil := formatRuntimeTime(now.Add(o.leaseDuration()))
	nowText := formatRuntimeTime(now)
	_, err := tx.ExecContext(ctx, claimOwnerLeaseSQL,
		epoch, o.InstanceID, nowText, nowText, leaseUntil,
	)
	if err != nil {
		return fmt.Errorf("claim runtime owner: %w", err)
	}
	return nil
}

func (o *RuntimeOwner) assertRecordedOwner(ctx context.Context, tx *sql.Tx, epoch string) error {
	var currentEpoch, currentInstance string
	if err := tx.QueryRowContext(ctx,
		"SELECT owner_epoch, owner_instance FROM runtime_owner WHERE singleton_id = 1",
	).Scan(&currentEpoch, &currentInstance); err != nil {
		return fmt.Errorf("read runtime owner after claim: %w", err)
	}
	if currentEpoch != epoch || currentInstance != o.InstanceID {
		return ErrRuntimeOwnerBusy
	}
	return nil
}

// Renew extends the lease only when this epoch still owns it and has not
// already expired. A zero-row update means ownership was lost.
func (o *RuntimeOwner) Renew(ctx context.Context, epoch string) error {
	if o == nil || o.DB == nil || epoch == "" {
		return fmt.Errorf("runtime owner is not configured")
	}
	now := o.now()
	result, err := o.DB.ExecContext(ctx, renewOwnerLeaseSQL,
		formatRuntimeTime(now), formatRuntimeTime(now.Add(o.leaseDuration())), epoch, o.InstanceID, formatRuntimeTime(now),
	)
	if err != nil {
		return fmt.Errorf("renew runtime owner: %w", err)
	}
	return requireOwnerMutation(result, "renewed")
}

// Release clears the singleton lease only for the owning epoch.
func (o *RuntimeOwner) Release(ctx context.Context, epoch string) error {
	if o == nil || o.DB == nil || epoch == "" {
		return fmt.Errorf("runtime owner is not configured")
	}
	now := o.now()
	result, err := o.DB.ExecContext(ctx, releaseOwnerLeaseSQL,
		formatRuntimeTime(now), formatRuntimeTime(now), epoch, o.InstanceID)
	if err != nil {
		return fmt.Errorf("release runtime owner: %w", err)
	}
	return requireOwnerMutation(result, "released")
}

// Assert verifies that epoch currently owns an unexpired lease inside tx.
// Callers use this as the write-fencing predicate for runtime-owned state.
func (o *RuntimeOwner) Assert(ctx context.Context, tx *sql.Tx, epoch string) error {
	if o == nil || tx == nil || epoch == "" {
		return fmt.Errorf("runtime owner is not configured")
	}
	var currentEpoch string
	if err := tx.QueryRowContext(ctx, `
		SELECT owner_epoch FROM runtime_owner
		WHERE singleton_id = 1 AND owner_epoch = ? AND owner_instance = ? AND lease_until > ?`,
		epoch, o.InstanceID, formatRuntimeTime(o.now()),
	).Scan(&currentEpoch); err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return ErrRuntimeOwnerBusy
		}
		return fmt.Errorf("assert runtime owner: %w", err)
	}
	return nil
}

func (o *RuntimeOwner) now() time.Time {
	if o.Now != nil {
		return o.Now().UTC()
	}
	return time.Now().UTC()
}

func (o *RuntimeOwner) leaseDuration() time.Duration {
	if o.Lease > 0 {
		return o.Lease
	}
	return time.Minute
}

func formatRuntimeTime(value time.Time) string {
	// runtime_owner timestamps are compared as SQLite TEXT. Fixed-width
	// nanoseconds preserve chronological ordering even when a time has no
	// fractional component.
	return value.UTC().Format("2006-01-02T15:04:05.000000000Z")
}

func (o *RuntimeOwner) claimAndRecoverTx(ctx context.Context, tx *sql.Tx, epoch string, now time.Time, recover func(*sql.Tx, time.Time) error) error {
	if err := o.claimTx(ctx, tx, epoch, now); err != nil {
		return err
	}
	if recover != nil {
		if err := recover(tx, now); err != nil {
			return err
		}
	}
	return o.Assert(ctx, tx, epoch)
}

const claimOwnerLeaseSQL = `
		INSERT INTO runtime_owner (
			singleton_id, owner_epoch, owner_instance, acquired_at,
			heartbeat_at, lease_until
		) VALUES (1, ?, ?, ?, ?, ?)
		ON CONFLICT(singleton_id) DO UPDATE SET
			owner_epoch = excluded.owner_epoch,
			owner_instance = excluded.owner_instance,
			acquired_at = CASE
				WHEN runtime_owner.owner_epoch = excluded.owner_epoch
					AND runtime_owner.owner_instance = excluded.owner_instance
					THEN runtime_owner.acquired_at
				ELSE excluded.acquired_at
			END,
			heartbeat_at = excluded.heartbeat_at,
			lease_until = excluded.lease_until
		WHERE (runtime_owner.owner_epoch = excluded.owner_epoch
			AND runtime_owner.owner_instance = excluded.owner_instance)
			OR (runtime_owner.owner_epoch <> excluded.owner_epoch
				AND runtime_owner.lease_until <= excluded.heartbeat_at)`

const renewOwnerLeaseSQL = `
		UPDATE runtime_owner
		SET heartbeat_at = ?, lease_until = ?
		WHERE singleton_id = 1 AND owner_epoch = ? AND owner_instance = ? AND lease_until > ?`

const releaseOwnerLeaseSQL = `
		UPDATE runtime_owner SET heartbeat_at = ?, lease_until = ?
		WHERE singleton_id = 1 AND owner_epoch = ? AND owner_instance = ?`

func requireOwnerMutation(result sql.Result, verb string) error {
	count, err := result.RowsAffected()
	if err != nil {
		return fmt.Errorf("count %s runtime owners: %w", verb, err)
	}
	if count != 1 {
		return ErrRuntimeOwnerBusy
	}
	return nil
}
