// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: runtime-v1.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EpisodeKind int32

const (
	EpisodeKind_EPISODE_KIND_UNSPECIFIED EpisodeKind = 0
	EpisodeKind_EPISODE_KIND_DIAGNOSE    EpisodeKind = 1
	EpisodeKind_EPISODE_KIND_RECONSIDER  EpisodeKind = 2
)

// Enum value maps for EpisodeKind.
var (
	EpisodeKind_name = map[int32]string{
		0: "EPISODE_KIND_UNSPECIFIED",
		1: "EPISODE_KIND_DIAGNOSE",
		2: "EPISODE_KIND_RECONSIDER",
	}
	EpisodeKind_value = map[string]int32{
		"EPISODE_KIND_UNSPECIFIED": 0,
		"EPISODE_KIND_DIAGNOSE":    1,
		"EPISODE_KIND_RECONSIDER":  2,
	}
)

func (x EpisodeKind) Enum() *EpisodeKind {
	p := new(EpisodeKind)
	*p = x
	return p
}

func (x EpisodeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EpisodeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_v1_proto_enumTypes[0].Descriptor()
}

func (EpisodeKind) Type() protoreflect.EnumType {
	return &file_runtime_v1_proto_enumTypes[0]
}

func (x EpisodeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EpisodeKind.Descriptor instead.
func (EpisodeKind) EnumDescriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{0}
}

type EpisodeLane int32

const (
	EpisodeLane_EPISODE_LANE_UNSPECIFIED EpisodeLane = 0
	EpisodeLane_EPISODE_LANE_FAST        EpisodeLane = 1
	EpisodeLane_EPISODE_LANE_DEEP        EpisodeLane = 2
	EpisodeLane_EPISODE_LANE_BATCH       EpisodeLane = 3
)

// Enum value maps for EpisodeLane.
var (
	EpisodeLane_name = map[int32]string{
		0: "EPISODE_LANE_UNSPECIFIED",
		1: "EPISODE_LANE_FAST",
		2: "EPISODE_LANE_DEEP",
		3: "EPISODE_LANE_BATCH",
	}
	EpisodeLane_value = map[string]int32{
		"EPISODE_LANE_UNSPECIFIED": 0,
		"EPISODE_LANE_FAST":        1,
		"EPISODE_LANE_DEEP":        2,
		"EPISODE_LANE_BATCH":       3,
	}
)

func (x EpisodeLane) Enum() *EpisodeLane {
	p := new(EpisodeLane)
	*p = x
	return p
}

func (x EpisodeLane) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EpisodeLane) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_v1_proto_enumTypes[1].Descriptor()
}

func (EpisodeLane) Type() protoreflect.EnumType {
	return &file_runtime_v1_proto_enumTypes[1]
}

func (x EpisodeLane) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EpisodeLane.Descriptor instead.
func (EpisodeLane) EnumDescriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{1}
}

type RiskClass int32

const (
	RiskClass_RISK_CLASS_UNSPECIFIED RiskClass = 0
	RiskClass_RISK_CLASS_R0          RiskClass = 1
	RiskClass_RISK_CLASS_R1          RiskClass = 2
	RiskClass_RISK_CLASS_R2          RiskClass = 3
	RiskClass_RISK_CLASS_R3          RiskClass = 4
	RiskClass_RISK_CLASS_R4          RiskClass = 5
)

// Enum value maps for RiskClass.
var (
	RiskClass_name = map[int32]string{
		0: "RISK_CLASS_UNSPECIFIED",
		1: "RISK_CLASS_R0",
		2: "RISK_CLASS_R1",
		3: "RISK_CLASS_R2",
		4: "RISK_CLASS_R3",
		5: "RISK_CLASS_R4",
	}
	RiskClass_value = map[string]int32{
		"RISK_CLASS_UNSPECIFIED": 0,
		"RISK_CLASS_R0":          1,
		"RISK_CLASS_R1":          2,
		"RISK_CLASS_R2":          3,
		"RISK_CLASS_R3":          4,
		"RISK_CLASS_R4":          5,
	}
)

func (x RiskClass) Enum() *RiskClass {
	p := new(RiskClass)
	*p = x
	return p
}

func (x RiskClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RiskClass) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_v1_proto_enumTypes[2].Descriptor()
}

func (RiskClass) Type() protoreflect.EnumType {
	return &file_runtime_v1_proto_enumTypes[2]
}

func (x RiskClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RiskClass.Descriptor instead.
func (RiskClass) EnumDescriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{2}
}

type DeltaLane int32

const (
	DeltaLane_DELTA_LANE_UNSPECIFIED DeltaLane = 0
	DeltaLane_DELTA_LANE_ASSISTANT   DeltaLane = 1
	DeltaLane_DELTA_LANE_COMMENTARY  DeltaLane = 2
)

// Enum value maps for DeltaLane.
var (
	DeltaLane_name = map[int32]string{
		0: "DELTA_LANE_UNSPECIFIED",
		1: "DELTA_LANE_ASSISTANT",
		2: "DELTA_LANE_COMMENTARY",
	}
	DeltaLane_value = map[string]int32{
		"DELTA_LANE_UNSPECIFIED": 0,
		"DELTA_LANE_ASSISTANT":   1,
		"DELTA_LANE_COMMENTARY":  2,
	}
)

func (x DeltaLane) Enum() *DeltaLane {
	p := new(DeltaLane)
	*p = x
	return p
}

func (x DeltaLane) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeltaLane) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_v1_proto_enumTypes[3].Descriptor()
}

func (DeltaLane) Type() protoreflect.EnumType {
	return &file_runtime_v1_proto_enumTypes[3]
}

func (x DeltaLane) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DeltaLane.Descriptor instead.
func (DeltaLane) EnumDescriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{3}
}

type ToolState int32

const (
	ToolState_TOOL_STATE_UNSPECIFIED ToolState = 0
	ToolState_TOOL_STATE_REQUESTED   ToolState = 1
	ToolState_TOOL_STATE_STARTED     ToolState = 2
	ToolState_TOOL_STATE_COMPLETED   ToolState = 3
	ToolState_TOOL_STATE_BLOCKED     ToolState = 4
)

// Enum value maps for ToolState.
var (
	ToolState_name = map[int32]string{
		0: "TOOL_STATE_UNSPECIFIED",
		1: "TOOL_STATE_REQUESTED",
		2: "TOOL_STATE_STARTED",
		3: "TOOL_STATE_COMPLETED",
		4: "TOOL_STATE_BLOCKED",
	}
	ToolState_value = map[string]int32{
		"TOOL_STATE_UNSPECIFIED": 0,
		"TOOL_STATE_REQUESTED":   1,
		"TOOL_STATE_STARTED":     2,
		"TOOL_STATE_COMPLETED":   3,
		"TOOL_STATE_BLOCKED":     4,
	}
)

func (x ToolState) Enum() *ToolState {
	p := new(ToolState)
	*p = x
	return p
}

func (x ToolState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ToolState) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_v1_proto_enumTypes[4].Descriptor()
}

func (ToolState) Type() protoreflect.EnumType {
	return &file_runtime_v1_proto_enumTypes[4]
}

func (x ToolState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ToolState.Descriptor instead.
func (ToolState) EnumDescriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{4}
}

type TerminalStatus int32

const (
	TerminalStatus_TERMINAL_STATUS_UNSPECIFIED      TerminalStatus = 0
	TerminalStatus_TERMINAL_STATUS_PRODUCED         TerminalStatus = 1
	TerminalStatus_TERMINAL_STATUS_DECLINED         TerminalStatus = 2
	TerminalStatus_TERMINAL_STATUS_CANCELLED        TerminalStatus = 3
	TerminalStatus_TERMINAL_STATUS_FAILED           TerminalStatus = 4
	TerminalStatus_TERMINAL_STATUS_TIMED_OUT        TerminalStatus = 5
	TerminalStatus_TERMINAL_STATUS_BUDGET_EXHAUSTED TerminalStatus = 6
)

// Enum value maps for TerminalStatus.
var (
	TerminalStatus_name = map[int32]string{
		0: "TERMINAL_STATUS_UNSPECIFIED",
		1: "TERMINAL_STATUS_PRODUCED",
		2: "TERMINAL_STATUS_DECLINED",
		3: "TERMINAL_STATUS_CANCELLED",
		4: "TERMINAL_STATUS_FAILED",
		5: "TERMINAL_STATUS_TIMED_OUT",
		6: "TERMINAL_STATUS_BUDGET_EXHAUSTED",
	}
	TerminalStatus_value = map[string]int32{
		"TERMINAL_STATUS_UNSPECIFIED":      0,
		"TERMINAL_STATUS_PRODUCED":         1,
		"TERMINAL_STATUS_DECLINED":         2,
		"TERMINAL_STATUS_CANCELLED":        3,
		"TERMINAL_STATUS_FAILED":           4,
		"TERMINAL_STATUS_TIMED_OUT":        5,
		"TERMINAL_STATUS_BUDGET_EXHAUSTED": 6,
	}
)

func (x TerminalStatus) Enum() *TerminalStatus {
	p := new(TerminalStatus)
	*p = x
	return p
}

func (x TerminalStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TerminalStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_runtime_v1_proto_enumTypes[5].Descriptor()
}

func (TerminalStatus) Type() protoreflect.EnumType {
	return &file_runtime_v1_proto_enumTypes[5]
}

func (x TerminalStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TerminalStatus.Descriptor instead.
func (TerminalStatus) EnumDescriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{5}
}

type HandshakeRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion           string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ContractVersion           string                 `protobuf:"bytes,2,opt,name=contract_version,json=contractVersion,proto3" json:"contract_version,omitempty"`
	WorkerId                  string                 `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	NonInteractive            bool                   `protobuf:"varint,4,opt,name=non_interactive,json=nonInteractive,proto3" json:"non_interactive,omitempty"`
	ShadowCapable             bool                   `protobuf:"varint,5,opt,name=shadow_capable,json=shadowCapable,proto3" json:"shadow_capable,omitempty"`
	CounterfactualCapable     bool                   `protobuf:"varint,6,opt,name=counterfactual_capable,json=counterfactualCapable,proto3" json:"counterfactual_capable,omitempty"`
	EmitsCompleteReplayLedger bool                   `protobuf:"varint,7,opt,name=emits_complete_replay_ledger,json=emitsCompleteReplayLedger,proto3" json:"emits_complete_replay_ledger,omitempty"`
	SupportsKinds             []EpisodeKind          `protobuf:"varint,8,rep,packed,name=supports_kinds,json=supportsKinds,proto3,enum=agenticstream.runtime.v1.EpisodeKind" json:"supports_kinds,omitempty"`
	RuntimeInstanceId         string                 `protobuf:"bytes,9,opt,name=runtime_instance_id,json=runtimeInstanceId,proto3" json:"runtime_instance_id,omitempty"`
	RequestedFeatures         []string               `protobuf:"bytes,10,rep,name=requested_features,json=requestedFeatures,proto3" json:"requested_features,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_runtime_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *HandshakeRequest) GetContractVersion() string {
	if x != nil {
		return x.ContractVersion
	}
	return ""
}

func (x *HandshakeRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *HandshakeRequest) GetNonInteractive() bool {
	if x != nil {
		return x.NonInteractive
	}
	return false
}

func (x *HandshakeRequest) GetShadowCapable() bool {
	if x != nil {
		return x.ShadowCapable
	}
	return false
}

func (x *HandshakeRequest) GetCounterfactualCapable() bool {
	if x != nil {
		return x.CounterfactualCapable
	}
	return false
}

func (x *HandshakeRequest) GetEmitsCompleteReplayLedger() bool {
	if x != nil {
		return x.EmitsCompleteReplayLedger
	}
	return false
}

func (x *HandshakeRequest) GetSupportsKinds() []EpisodeKind {
	if x != nil {
		return x.SupportsKinds
	}
	return nil
}

func (x *HandshakeRequest) GetRuntimeInstanceId() string {
	if x != nil {
		return x.RuntimeInstanceId
	}
	return ""
}

func (x *HandshakeRequest) GetRequestedFeatures() []string {
	if x != nil {
		return x.RequestedFeatures
	}
	return nil
}

type HandshakeResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion   string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ContractVersion   string                 `protobuf:"bytes,2,opt,name=contract_version,json=contractVersion,proto3" json:"contract_version,omitempty"`
	WorkerName        string                 `protobuf:"bytes,3,opt,name=worker_name,json=workerName,proto3" json:"worker_name,omitempty"`
	WorkerVersion     string                 `protobuf:"bytes,4,opt,name=worker_version,json=workerVersion,proto3" json:"worker_version,omitempty"`
	SupportedFeatures []string               `protobuf:"bytes,5,rep,name=supported_features,json=supportedFeatures,proto3" json:"supported_features,omitempty"`
	MaxRequestBytes   uint64                 `protobuf:"varint,6,opt,name=max_request_bytes,json=maxRequestBytes,proto3" json:"max_request_bytes,omitempty"`
	MaxEventBytes     uint64                 `protobuf:"varint,7,opt,name=max_event_bytes,json=maxEventBytes,proto3" json:"max_event_bytes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_runtime_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *HandshakeResponse) GetContractVersion() string {
	if x != nil {
		return x.ContractVersion
	}
	return ""
}

func (x *HandshakeResponse) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

func (x *HandshakeResponse) GetWorkerVersion() string {
	if x != nil {
		return x.WorkerVersion
	}
	return ""
}

func (x *HandshakeResponse) GetSupportedFeatures() []string {
	if x != nil {
		return x.SupportedFeatures
	}
	return nil
}

func (x *HandshakeResponse) GetMaxRequestBytes() uint64 {
	if x != nil {
		return x.MaxRequestBytes
	}
	return 0
}

func (x *HandshakeResponse) GetMaxEventBytes() uint64 {
	if x != nil {
		return x.MaxEventBytes
	}
	return 0
}

type EpisodeRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion  string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	EpisodeId        string                 `protobuf:"bytes,2,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	TriggerId        string                 `protobuf:"bytes,3,opt,name=trigger_id,json=triggerId,proto3" json:"trigger_id,omitempty"`
	TenantId         string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SituationId      string                 `protobuf:"bytes,5,opt,name=situation_id,json=situationId,proto3" json:"situation_id,omitempty"`
	SituationVersion uint64                 `protobuf:"varint,6,opt,name=situation_version,json=situationVersion,proto3" json:"situation_version,omitempty"`
	// Canonical JSON documents validated by the core before dispatch.
	SnapshotJson         []byte                 `protobuf:"bytes,10,opt,name=snapshot_json,json=snapshotJson,proto3" json:"snapshot_json,omitempty"`
	SnapshotSha256       []byte                 `protobuf:"bytes,11,opt,name=snapshot_sha256,json=snapshotSha256,proto3" json:"snapshot_sha256,omitempty"`
	DecisionSchemaJson   []byte                 `protobuf:"bytes,12,opt,name=decision_schema_json,json=decisionSchemaJson,proto3" json:"decision_schema_json,omitempty"`
	DecisionSchemaSha256 []byte                 `protobuf:"bytes,13,opt,name=decision_schema_sha256,json=decisionSchemaSha256,proto3" json:"decision_schema_sha256,omitempty"`
	ToolCatalogJson      []byte                 `protobuf:"bytes,14,opt,name=tool_catalog_json,json=toolCatalogJson,proto3" json:"tool_catalog_json,omitempty"`
	ToolCatalogSha256    []byte                 `protobuf:"bytes,15,opt,name=tool_catalog_sha256,json=toolCatalogSha256,proto3" json:"tool_catalog_sha256,omitempty"`
	SpecSha256           []byte                 `protobuf:"bytes,16,opt,name=spec_sha256,json=specSha256,proto3" json:"spec_sha256,omitempty"`
	Objective            string                 `protobuf:"bytes,20,opt,name=objective,proto3" json:"objective,omitempty"`
	ExecutorName         string                 `protobuf:"bytes,21,opt,name=executor_name,json=executorName,proto3" json:"executor_name,omitempty"`
	ExecutorVersion      string                 `protobuf:"bytes,22,opt,name=executor_version,json=executorVersion,proto3" json:"executor_version,omitempty"`
	ModelPolicy          string                 `protobuf:"bytes,23,opt,name=model_policy,json=modelPolicy,proto3" json:"model_policy,omitempty"`
	PromptVersion        string                 `protobuf:"bytes,24,opt,name=prompt_version,json=promptVersion,proto3" json:"prompt_version,omitempty"`
	Budget               *EpisodeBudget         `protobuf:"bytes,30,opt,name=budget,proto3" json:"budget,omitempty"`
	Deadline             *timestamppb.Timestamp `protobuf:"bytes,31,opt,name=deadline,proto3" json:"deadline,omitempty"`
	SupersessionKey      string                 `protobuf:"bytes,32,opt,name=supersession_key,json=supersessionKey,proto3" json:"supersession_key,omitempty"`
	Traceparent          string                 `protobuf:"bytes,33,opt,name=traceparent,proto3" json:"traceparent,omitempty"`
	Tracestate           string                 `protobuf:"bytes,34,opt,name=tracestate,proto3" json:"tracestate,omitempty"`
	// The endpoint is normally a Unix domain socket. The token is opaque,
	// short-lived, and must never be logged or persisted by the worker.
	EvidenceToolsEndpoint string             `protobuf:"bytes,40,opt,name=evidence_tools_endpoint,json=evidenceToolsEndpoint,proto3" json:"evidence_tools_endpoint,omitempty"`
	CapabilityToken       []byte             `protobuf:"bytes,41,opt,name=capability_token,json=capabilityToken,proto3" json:"capability_token,omitempty"`
	Kind                  EpisodeKind        `protobuf:"varint,50,opt,name=kind,proto3,enum=agenticstream.runtime.v1.EpisodeKind" json:"kind,omitempty"`
	Lane                  EpisodeLane        `protobuf:"varint,51,opt,name=lane,proto3,enum=agenticstream.runtime.v1.EpisodeLane" json:"lane,omitempty"`
	RiskCeiling           RiskClass          `protobuf:"varint,52,opt,name=risk_ceiling,json=riskCeiling,proto3,enum=agenticstream.runtime.v1.RiskClass" json:"risk_ceiling,omitempty"`
	AllowedIntentTypes    []string           `protobuf:"bytes,53,rep,name=allowed_intent_types,json=allowedIntentTypes,proto3" json:"allowed_intent_types,omitempty"`
	CancellationKey       string             `protobuf:"bytes,54,opt,name=cancellation_key,json=cancellationKey,proto3" json:"cancellation_key,omitempty"`
	AttemptId             string             `protobuf:"bytes,55,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Fence                 uint64             `protobuf:"varint,56,opt,name=fence,proto3" json:"fence,omitempty"`
	EvidenceTimeRange     *EvidenceTimeRange `protobuf:"bytes,57,opt,name=evidence_time_range,json=evidenceTimeRange,proto3" json:"evidence_time_range,omitempty"`
	Reconsideration       *Reconsideration   `protobuf:"bytes,58,opt,name=reconsideration,proto3" json:"reconsideration,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *EpisodeRequest) Reset() {
	*x = EpisodeRequest{}
	mi := &file_runtime_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpisodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodeRequest) ProtoMessage() {}

func (x *EpisodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpisodeRequest.ProtoReflect.Descriptor instead.
func (*EpisodeRequest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{2}
}

func (x *EpisodeRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *EpisodeRequest) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

func (x *EpisodeRequest) GetTriggerId() string {
	if x != nil {
		return x.TriggerId
	}
	return ""
}

func (x *EpisodeRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EpisodeRequest) GetSituationId() string {
	if x != nil {
		return x.SituationId
	}
	return ""
}

func (x *EpisodeRequest) GetSituationVersion() uint64 {
	if x != nil {
		return x.SituationVersion
	}
	return 0
}

func (x *EpisodeRequest) GetSnapshotJson() []byte {
	if x != nil {
		return x.SnapshotJson
	}
	return nil
}

func (x *EpisodeRequest) GetSnapshotSha256() []byte {
	if x != nil {
		return x.SnapshotSha256
	}
	return nil
}

func (x *EpisodeRequest) GetDecisionSchemaJson() []byte {
	if x != nil {
		return x.DecisionSchemaJson
	}
	return nil
}

func (x *EpisodeRequest) GetDecisionSchemaSha256() []byte {
	if x != nil {
		return x.DecisionSchemaSha256
	}
	return nil
}

func (x *EpisodeRequest) GetToolCatalogJson() []byte {
	if x != nil {
		return x.ToolCatalogJson
	}
	return nil
}

func (x *EpisodeRequest) GetToolCatalogSha256() []byte {
	if x != nil {
		return x.ToolCatalogSha256
	}
	return nil
}

func (x *EpisodeRequest) GetSpecSha256() []byte {
	if x != nil {
		return x.SpecSha256
	}
	return nil
}

func (x *EpisodeRequest) GetObjective() string {
	if x != nil {
		return x.Objective
	}
	return ""
}

func (x *EpisodeRequest) GetExecutorName() string {
	if x != nil {
		return x.ExecutorName
	}
	return ""
}

func (x *EpisodeRequest) GetExecutorVersion() string {
	if x != nil {
		return x.ExecutorVersion
	}
	return ""
}

func (x *EpisodeRequest) GetModelPolicy() string {
	if x != nil {
		return x.ModelPolicy
	}
	return ""
}

func (x *EpisodeRequest) GetPromptVersion() string {
	if x != nil {
		return x.PromptVersion
	}
	return ""
}

func (x *EpisodeRequest) GetBudget() *EpisodeBudget {
	if x != nil {
		return x.Budget
	}
	return nil
}

func (x *EpisodeRequest) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *EpisodeRequest) GetSupersessionKey() string {
	if x != nil {
		return x.SupersessionKey
	}
	return ""
}

func (x *EpisodeRequest) GetTraceparent() string {
	if x != nil {
		return x.Traceparent
	}
	return ""
}

func (x *EpisodeRequest) GetTracestate() string {
	if x != nil {
		return x.Tracestate
	}
	return ""
}

func (x *EpisodeRequest) GetEvidenceToolsEndpoint() string {
	if x != nil {
		return x.EvidenceToolsEndpoint
	}
	return ""
}

func (x *EpisodeRequest) GetCapabilityToken() []byte {
	if x != nil {
		return x.CapabilityToken
	}
	return nil
}

func (x *EpisodeRequest) GetKind() EpisodeKind {
	if x != nil {
		return x.Kind
	}
	return EpisodeKind_EPISODE_KIND_UNSPECIFIED
}

func (x *EpisodeRequest) GetLane() EpisodeLane {
	if x != nil {
		return x.Lane
	}
	return EpisodeLane_EPISODE_LANE_UNSPECIFIED
}

func (x *EpisodeRequest) GetRiskCeiling() RiskClass {
	if x != nil {
		return x.RiskCeiling
	}
	return RiskClass_RISK_CLASS_UNSPECIFIED
}

func (x *EpisodeRequest) GetAllowedIntentTypes() []string {
	if x != nil {
		return x.AllowedIntentTypes
	}
	return nil
}

func (x *EpisodeRequest) GetCancellationKey() string {
	if x != nil {
		return x.CancellationKey
	}
	return ""
}

func (x *EpisodeRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *EpisodeRequest) GetFence() uint64 {
	if x != nil {
		return x.Fence
	}
	return 0
}

func (x *EpisodeRequest) GetEvidenceTimeRange() *EvidenceTimeRange {
	if x != nil {
		return x.EvidenceTimeRange
	}
	return nil
}

func (x *EpisodeRequest) GetReconsideration() *Reconsideration {
	if x != nil {
		return x.Reconsideration
	}
	return nil
}

type EvidenceTimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	Until         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=until,proto3" json:"until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidenceTimeRange) Reset() {
	*x = EvidenceTimeRange{}
	mi := &file_runtime_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceTimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceTimeRange) ProtoMessage() {}

func (x *EvidenceTimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceTimeRange.ProtoReflect.Descriptor instead.
func (*EvidenceTimeRange) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{3}
}

func (x *EvidenceTimeRange) GetFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *EvidenceTimeRange) GetUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.Until
	}
	return nil
}

type Reconsideration struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	PriorDecisionJson   []byte                 `protobuf:"bytes,1,opt,name=prior_decision_json,json=priorDecisionJson,proto3" json:"prior_decision_json,omitempty"`
	ExecutedCommandJson [][]byte               `protobuf:"bytes,2,rep,name=executed_command_json,json=executedCommandJson,proto3" json:"executed_command_json,omitempty"`
	ObservedOutcomeJson [][]byte               `protobuf:"bytes,3,rep,name=observed_outcome_json,json=observedOutcomeJson,proto3" json:"observed_outcome_json,omitempty"`
	CorrectionJson      []byte                 `protobuf:"bytes,4,opt,name=correction_json,json=correctionJson,proto3" json:"correction_json,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Reconsideration) Reset() {
	*x = Reconsideration{}
	mi := &file_runtime_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reconsideration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reconsideration) ProtoMessage() {}

func (x *Reconsideration) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reconsideration.ProtoReflect.Descriptor instead.
func (*Reconsideration) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{4}
}

func (x *Reconsideration) GetPriorDecisionJson() []byte {
	if x != nil {
		return x.PriorDecisionJson
	}
	return nil
}

func (x *Reconsideration) GetExecutedCommandJson() [][]byte {
	if x != nil {
		return x.ExecutedCommandJson
	}
	return nil
}

func (x *Reconsideration) GetObservedOutcomeJson() [][]byte {
	if x != nil {
		return x.ObservedOutcomeJson
	}
	return nil
}

func (x *Reconsideration) GetCorrectionJson() []byte {
	if x != nil {
		return x.CorrectionJson
	}
	return nil
}

type EpisodeBudget struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	WallTime                *durationpb.Duration   `protobuf:"bytes,1,opt,name=wall_time,json=wallTime,proto3" json:"wall_time,omitempty"`
	MaxModelCalls           uint32                 `protobuf:"varint,2,opt,name=max_model_calls,json=maxModelCalls,proto3" json:"max_model_calls,omitempty"`
	MaxInputTokens          uint64                 `protobuf:"varint,3,opt,name=max_input_tokens,json=maxInputTokens,proto3" json:"max_input_tokens,omitempty"`
	MaxOutputTokens         uint64                 `protobuf:"varint,4,opt,name=max_output_tokens,json=maxOutputTokens,proto3" json:"max_output_tokens,omitempty"`
	MaxToolCalls            uint32                 `protobuf:"varint,5,opt,name=max_tool_calls,json=maxToolCalls,proto3" json:"max_tool_calls,omitempty"`
	MaxToolResultBytes      uint64                 `protobuf:"varint,6,opt,name=max_tool_result_bytes,json=maxToolResultBytes,proto3" json:"max_tool_result_bytes,omitempty"`
	MaxTotalToolResultBytes uint64                 `protobuf:"varint,7,opt,name=max_total_tool_result_bytes,json=maxTotalToolResultBytes,proto3" json:"max_total_tool_result_bytes,omitempty"`
	MaxProviderRetries      uint32                 `protobuf:"varint,8,opt,name=max_provider_retries,json=maxProviderRetries,proto3" json:"max_provider_retries,omitempty"`
	MaxCostMicrounits       uint64                 `protobuf:"varint,9,opt,name=max_cost_microunits,json=maxCostMicrounits,proto3" json:"max_cost_microunits,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *EpisodeBudget) Reset() {
	*x = EpisodeBudget{}
	mi := &file_runtime_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpisodeBudget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodeBudget) ProtoMessage() {}

func (x *EpisodeBudget) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpisodeBudget.ProtoReflect.Descriptor instead.
func (*EpisodeBudget) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{5}
}

func (x *EpisodeBudget) GetWallTime() *durationpb.Duration {
	if x != nil {
		return x.WallTime
	}
	return nil
}

func (x *EpisodeBudget) GetMaxModelCalls() uint32 {
	if x != nil {
		return x.MaxModelCalls
	}
	return 0
}

func (x *EpisodeBudget) GetMaxInputTokens() uint64 {
	if x != nil {
		return x.MaxInputTokens
	}
	return 0
}

func (x *EpisodeBudget) GetMaxOutputTokens() uint64 {
	if x != nil {
		return x.MaxOutputTokens
	}
	return 0
}

func (x *EpisodeBudget) GetMaxToolCalls() uint32 {
	if x != nil {
		return x.MaxToolCalls
	}
	return 0
}

func (x *EpisodeBudget) GetMaxToolResultBytes() uint64 {
	if x != nil {
		return x.MaxToolResultBytes
	}
	return 0
}

func (x *EpisodeBudget) GetMaxTotalToolResultBytes() uint64 {
	if x != nil {
		return x.MaxTotalToolResultBytes
	}
	return 0
}

func (x *EpisodeBudget) GetMaxProviderRetries() uint32 {
	if x != nil {
		return x.MaxProviderRetries
	}
	return 0
}

func (x *EpisodeBudget) GetMaxCostMicrounits() uint64 {
	if x != nil {
		return x.MaxCostMicrounits
	}
	return 0
}

type EpisodeEvent struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	EpisodeId  string                 `protobuf:"bytes,1,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	Sequence   uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	OccurredAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	AttemptId  string                 `protobuf:"bytes,4,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Fence      uint64                 `protobuf:"varint,5,opt,name=fence,proto3" json:"fence,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*EpisodeEvent_Started
	//	*EpisodeEvent_ModelStarted
	//	*EpisodeEvent_ModelDelta
	//	*EpisodeEvent_ModelCompleted
	//	*EpisodeEvent_Tool
	//	*EpisodeEvent_ToolProgress
	//	*EpisodeEvent_Budget
	//	*EpisodeEvent_Decision
	//	*EpisodeEvent_Diagnostic
	//	*EpisodeEvent_Terminal
	//	*EpisodeEvent_Cancelling
	Payload       isEpisodeEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpisodeEvent) Reset() {
	*x = EpisodeEvent{}
	mi := &file_runtime_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpisodeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodeEvent) ProtoMessage() {}

func (x *EpisodeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpisodeEvent.ProtoReflect.Descriptor instead.
func (*EpisodeEvent) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{6}
}

func (x *EpisodeEvent) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

func (x *EpisodeEvent) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *EpisodeEvent) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *EpisodeEvent) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *EpisodeEvent) GetFence() uint64 {
	if x != nil {
		return x.Fence
	}
	return 0
}

func (x *EpisodeEvent) GetPayload() isEpisodeEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EpisodeEvent) GetStarted() *EpisodeStarted {
	if x != nil {
		if x, ok := x.Payload.(*EpisodeEvent_Started); ok {
			return x.Started
		}
	}
	return nil
}

func (x *EpisodeEvent) GetModelStarted() *ModelStarted {
	if x != nil {
		if x, ok := x.Payload.(*EpisodeEvent_ModelStarted); ok {
			return x.ModelStarted
		}
	}
	return nil
}

func (x *EpisodeEvent) GetModelDelta() *ModelDelta {
	if x != nil {
		if x, ok := x.Payload.(*EpisodeEvent_ModelDelta); ok {
			return x.ModelDelta
		}
	}
	return nil
}

func (x *EpisodeEvent) GetModelCompleted() *ModelCompleted {
	if x != nil {
		if x, ok := x.Payload.(*EpisodeEvent_ModelCompleted); ok {
			return x.ModelCompleted
		}
	}
	return nil
}

func (x *EpisodeEvent) GetTool() *ToolLifecycle {
	if x != nil {
		if x, ok := x.Payload.(*EpisodeEvent_Tool); ok {
			return x.Tool
		}
	}
	return nil
}

func (x *EpisodeEvent) GetToolProgress() *ToolProgress {
	if x != nil {
		if x, ok := x.Payload.(*EpisodeEvent_ToolProgress); ok {
			return x.ToolProgress
		}
	}
	return nil
}

func (x *EpisodeEvent) GetBudget() *BudgetUpdated {
	if x != nil {
		if x, ok := x.Payload.(*EpisodeEvent_Budget); ok {
			return x.Budget
		}
	}
	return nil
}

func (x *EpisodeEvent) GetDecision() *DecisionProposed {
	if x != nil {
		if x, ok := x.Payload.(*EpisodeEvent_Decision); ok {
			return x.Decision
		}
	}
	return nil
}

func (x *EpisodeEvent) GetDiagnostic() *Diagnostic {
	if x != nil {
		if x, ok := x.Payload.(*EpisodeEvent_Diagnostic); ok {
			return x.Diagnostic
		}
	}
	return nil
}

func (x *EpisodeEvent) GetTerminal() *Terminal {
	if x != nil {
		if x, ok := x.Payload.(*EpisodeEvent_Terminal); ok {
			return x.Terminal
		}
	}
	return nil
}

func (x *EpisodeEvent) GetCancelling() *EpisodeCancelling {
	if x != nil {
		if x, ok := x.Payload.(*EpisodeEvent_Cancelling); ok {
			return x.Cancelling
		}
	}
	return nil
}

type isEpisodeEvent_Payload interface {
	isEpisodeEvent_Payload()
}

type EpisodeEvent_Started struct {
	Started *EpisodeStarted `protobuf:"bytes,10,opt,name=started,proto3,oneof"`
}

type EpisodeEvent_ModelStarted struct {
	ModelStarted *ModelStarted `protobuf:"bytes,11,opt,name=model_started,json=modelStarted,proto3,oneof"`
}

type EpisodeEvent_ModelDelta struct {
	ModelDelta *ModelDelta `protobuf:"bytes,12,opt,name=model_delta,json=modelDelta,proto3,oneof"`
}

type EpisodeEvent_ModelCompleted struct {
	ModelCompleted *ModelCompleted `protobuf:"bytes,13,opt,name=model_completed,json=modelCompleted,proto3,oneof"`
}

type EpisodeEvent_Tool struct {
	Tool *ToolLifecycle `protobuf:"bytes,14,opt,name=tool,proto3,oneof"`
}

type EpisodeEvent_ToolProgress struct {
	ToolProgress *ToolProgress `protobuf:"bytes,20,opt,name=tool_progress,json=toolProgress,proto3,oneof"`
}

type EpisodeEvent_Budget struct {
	Budget *BudgetUpdated `protobuf:"bytes,15,opt,name=budget,proto3,oneof"`
}

type EpisodeEvent_Decision struct {
	Decision *DecisionProposed `protobuf:"bytes,16,opt,name=decision,proto3,oneof"`
}

type EpisodeEvent_Diagnostic struct {
	Diagnostic *Diagnostic `protobuf:"bytes,17,opt,name=diagnostic,proto3,oneof"`
}

type EpisodeEvent_Terminal struct {
	Terminal *Terminal `protobuf:"bytes,18,opt,name=terminal,proto3,oneof"`
}

type EpisodeEvent_Cancelling struct {
	Cancelling *EpisodeCancelling `protobuf:"bytes,19,opt,name=cancelling,proto3,oneof"`
}

func (*EpisodeEvent_Started) isEpisodeEvent_Payload() {}

func (*EpisodeEvent_ModelStarted) isEpisodeEvent_Payload() {}

func (*EpisodeEvent_ModelDelta) isEpisodeEvent_Payload() {}

func (*EpisodeEvent_ModelCompleted) isEpisodeEvent_Payload() {}

func (*EpisodeEvent_Tool) isEpisodeEvent_Payload() {}

func (*EpisodeEvent_ToolProgress) isEpisodeEvent_Payload() {}

func (*EpisodeEvent_Budget) isEpisodeEvent_Payload() {}

func (*EpisodeEvent_Decision) isEpisodeEvent_Payload() {}

func (*EpisodeEvent_Diagnostic) isEpisodeEvent_Payload() {}

func (*EpisodeEvent_Terminal) isEpisodeEvent_Payload() {}

func (*EpisodeEvent_Cancelling) isEpisodeEvent_Payload() {}

type EpisodeStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerName    string                 `protobuf:"bytes,1,opt,name=worker_name,json=workerName,proto3" json:"worker_name,omitempty"`
	WorkerVersion string                 `protobuf:"bytes,2,opt,name=worker_version,json=workerVersion,proto3" json:"worker_version,omitempty"`
	ModelProvider string                 `protobuf:"bytes,3,opt,name=model_provider,json=modelProvider,proto3" json:"model_provider,omitempty"`
	ModelId       string                 `protobuf:"bytes,4,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpisodeStarted) Reset() {
	*x = EpisodeStarted{}
	mi := &file_runtime_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpisodeStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodeStarted) ProtoMessage() {}

func (x *EpisodeStarted) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpisodeStarted.ProtoReflect.Descriptor instead.
func (*EpisodeStarted) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{7}
}

func (x *EpisodeStarted) GetWorkerName() string {
	if x != nil {
		return x.WorkerName
	}
	return ""
}

func (x *EpisodeStarted) GetWorkerVersion() string {
	if x != nil {
		return x.WorkerVersion
	}
	return ""
}

func (x *EpisodeStarted) GetModelProvider() string {
	if x != nil {
		return x.ModelProvider
	}
	return ""
}

func (x *EpisodeStarted) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

type ModelStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ordinal       uint32                 `protobuf:"varint,1,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	ModelId       string                 `protobuf:"bytes,3,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	RequestSha256 []byte                 `protobuf:"bytes,4,opt,name=request_sha256,json=requestSha256,proto3" json:"request_sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelStarted) Reset() {
	*x = ModelStarted{}
	mi := &file_runtime_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelStarted) ProtoMessage() {}

func (x *ModelStarted) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelStarted.ProtoReflect.Descriptor instead.
func (*ModelStarted) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{8}
}

func (x *ModelStarted) GetOrdinal() uint32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *ModelStarted) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ModelStarted) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *ModelStarted) GetRequestSha256() []byte {
	if x != nil {
		return x.RequestSha256
	}
	return nil
}

type ModelDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelOrdinal  uint32                 `protobuf:"varint,1,opt,name=model_ordinal,json=modelOrdinal,proto3" json:"model_ordinal,omitempty"`
	Lane          DeltaLane              `protobuf:"varint,2,opt,name=lane,proto3,enum=agenticstream.runtime.v1.DeltaLane" json:"lane,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelDelta) Reset() {
	*x = ModelDelta{}
	mi := &file_runtime_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelDelta) ProtoMessage() {}

func (x *ModelDelta) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelDelta.ProtoReflect.Descriptor instead.
func (*ModelDelta) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{9}
}

func (x *ModelDelta) GetModelOrdinal() uint32 {
	if x != nil {
		return x.ModelOrdinal
	}
	return 0
}

func (x *ModelDelta) GetLane() DeltaLane {
	if x != nil {
		return x.Lane
	}
	return DeltaLane_DELTA_LANE_UNSPECIFIED
}

func (x *ModelDelta) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ModelCompleted struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Ordinal        uint32                 `protobuf:"varint,1,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	FinishReason   string                 `protobuf:"bytes,2,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	Usage          *Usage                 `protobuf:"bytes,3,opt,name=usage,proto3" json:"usage,omitempty"`
	ResponseSha256 []byte                 `protobuf:"bytes,4,opt,name=response_sha256,json=responseSha256,proto3" json:"response_sha256,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ModelCompleted) Reset() {
	*x = ModelCompleted{}
	mi := &file_runtime_v1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelCompleted) ProtoMessage() {}

func (x *ModelCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelCompleted.ProtoReflect.Descriptor instead.
func (*ModelCompleted) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{10}
}

func (x *ModelCompleted) GetOrdinal() uint32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *ModelCompleted) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *ModelCompleted) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *ModelCompleted) GetResponseSha256() []byte {
	if x != nil {
		return x.ResponseSha256
	}
	return nil
}

type ToolLifecycle struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CallId           string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	ToolName         string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	State            ToolState              `protobuf:"varint,3,opt,name=state,proto3,enum=agenticstream.runtime.v1.ToolState" json:"state,omitempty"`
	ArgumentsSha256  []byte                 `protobuf:"bytes,4,opt,name=arguments_sha256,json=argumentsSha256,proto3" json:"arguments_sha256,omitempty"`
	ResultSha256     []byte                 `protobuf:"bytes,5,opt,name=result_sha256,json=resultSha256,proto3" json:"result_sha256,omitempty"`
	IsError          bool                   `protobuf:"varint,6,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	ExecutionStarted bool                   `protobuf:"varint,7,opt,name=execution_started,json=executionStarted,proto3" json:"execution_started,omitempty"`
	ErrorCode        string                 `protobuf:"bytes,8,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ToolLifecycle) Reset() {
	*x = ToolLifecycle{}
	mi := &file_runtime_v1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolLifecycle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolLifecycle) ProtoMessage() {}

func (x *ToolLifecycle) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolLifecycle.ProtoReflect.Descriptor instead.
func (*ToolLifecycle) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{11}
}

func (x *ToolLifecycle) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolLifecycle) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolLifecycle) GetState() ToolState {
	if x != nil {
		return x.State
	}
	return ToolState_TOOL_STATE_UNSPECIFIED
}

func (x *ToolLifecycle) GetArgumentsSha256() []byte {
	if x != nil {
		return x.ArgumentsSha256
	}
	return nil
}

func (x *ToolLifecycle) GetResultSha256() []byte {
	if x != nil {
		return x.ResultSha256
	}
	return nil
}

func (x *ToolLifecycle) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *ToolLifecycle) GetExecutionStarted() bool {
	if x != nil {
		return x.ExecutionStarted
	}
	return false
}

func (x *ToolLifecycle) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type ToolProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	BytesRead     uint64                 `protobuf:"varint,2,opt,name=bytes_read,json=bytesRead,proto3" json:"bytes_read,omitempty"`
	RowsRead      uint64                 `protobuf:"varint,3,opt,name=rows_read,json=rowsRead,proto3" json:"rows_read,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolProgress) Reset() {
	*x = ToolProgress{}
	mi := &file_runtime_v1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolProgress) ProtoMessage() {}

func (x *ToolProgress) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolProgress.ProtoReflect.Descriptor instead.
func (*ToolProgress) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{12}
}

func (x *ToolProgress) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *ToolProgress) GetBytesRead() uint64 {
	if x != nil {
		return x.BytesRead
	}
	return 0
}

func (x *ToolProgress) GetRowsRead() uint64 {
	if x != nil {
		return x.RowsRead
	}
	return 0
}

type Usage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InputTokens       uint64                 `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens      uint64                 `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	CachedInputTokens uint64                 `protobuf:"varint,3,opt,name=cached_input_tokens,json=cachedInputTokens,proto3" json:"cached_input_tokens,omitempty"`
	ReasoningTokens   uint64                 `protobuf:"varint,4,opt,name=reasoning_tokens,json=reasoningTokens,proto3" json:"reasoning_tokens,omitempty"`
	CostMicrounits    uint64                 `protobuf:"varint,5,opt,name=cost_microunits,json=costMicrounits,proto3" json:"cost_microunits,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_runtime_v1_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{13}
}

func (x *Usage) GetInputTokens() uint64 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *Usage) GetOutputTokens() uint64 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *Usage) GetCachedInputTokens() uint64 {
	if x != nil {
		return x.CachedInputTokens
	}
	return 0
}

func (x *Usage) GetReasoningTokens() uint64 {
	if x != nil {
		return x.ReasoningTokens
	}
	return 0
}

func (x *Usage) GetCostMicrounits() uint64 {
	if x != nil {
		return x.CostMicrounits
	}
	return 0
}

type BudgetUpdated struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Remaining           *EpisodeBudget         `protobuf:"bytes,1,opt,name=remaining,proto3" json:"remaining,omitempty"`
	CumulativeUsage     *Usage                 `protobuf:"bytes,2,opt,name=cumulative_usage,json=cumulativeUsage,proto3" json:"cumulative_usage,omitempty"`
	ModelCallsUsed      uint32                 `protobuf:"varint,3,opt,name=model_calls_used,json=modelCallsUsed,proto3" json:"model_calls_used,omitempty"`
	ToolCallsUsed       uint32                 `protobuf:"varint,4,opt,name=tool_calls_used,json=toolCallsUsed,proto3" json:"tool_calls_used,omitempty"`
	ToolResultBytesUsed uint64                 `protobuf:"varint,5,opt,name=tool_result_bytes_used,json=toolResultBytesUsed,proto3" json:"tool_result_bytes_used,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *BudgetUpdated) Reset() {
	*x = BudgetUpdated{}
	mi := &file_runtime_v1_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BudgetUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BudgetUpdated) ProtoMessage() {}

func (x *BudgetUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BudgetUpdated.ProtoReflect.Descriptor instead.
func (*BudgetUpdated) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{14}
}

func (x *BudgetUpdated) GetRemaining() *EpisodeBudget {
	if x != nil {
		return x.Remaining
	}
	return nil
}

func (x *BudgetUpdated) GetCumulativeUsage() *Usage {
	if x != nil {
		return x.CumulativeUsage
	}
	return nil
}

func (x *BudgetUpdated) GetModelCallsUsed() uint32 {
	if x != nil {
		return x.ModelCallsUsed
	}
	return 0
}

func (x *BudgetUpdated) GetToolCallsUsed() uint32 {
	if x != nil {
		return x.ToolCallsUsed
	}
	return 0
}

func (x *BudgetUpdated) GetToolResultBytesUsed() uint64 {
	if x != nil {
		return x.ToolResultBytesUsed
	}
	return 0
}

type DecisionProposed struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DecisionJson   []byte                 `protobuf:"bytes,1,opt,name=decision_json,json=decisionJson,proto3" json:"decision_json,omitempty"`
	DecisionSha256 []byte                 `protobuf:"bytes,2,opt,name=decision_sha256,json=decisionSha256,proto3" json:"decision_sha256,omitempty"`
	EpisodeId      string                 `protobuf:"bytes,3,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	AttemptId      string                 `protobuf:"bytes,4,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Fence          uint64                 `protobuf:"varint,5,opt,name=fence,proto3" json:"fence,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DecisionProposed) Reset() {
	*x = DecisionProposed{}
	mi := &file_runtime_v1_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionProposed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionProposed) ProtoMessage() {}

func (x *DecisionProposed) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionProposed.ProtoReflect.Descriptor instead.
func (*DecisionProposed) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{15}
}

func (x *DecisionProposed) GetDecisionJson() []byte {
	if x != nil {
		return x.DecisionJson
	}
	return nil
}

func (x *DecisionProposed) GetDecisionSha256() []byte {
	if x != nil {
		return x.DecisionSha256
	}
	return nil
}

func (x *DecisionProposed) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

func (x *DecisionProposed) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *DecisionProposed) GetFence() uint64 {
	if x != nil {
		return x.Fence
	}
	return 0
}

type EpisodeCancelling struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReasonCode    string                 `protobuf:"bytes,1,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpisodeCancelling) Reset() {
	*x = EpisodeCancelling{}
	mi := &file_runtime_v1_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpisodeCancelling) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodeCancelling) ProtoMessage() {}

func (x *EpisodeCancelling) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpisodeCancelling.ProtoReflect.Descriptor instead.
func (*EpisodeCancelling) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{16}
}

func (x *EpisodeCancelling) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *EpisodeCancelling) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type Diagnostic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	DiagnosticRef string                 `protobuf:"bytes,4,opt,name=diagnostic_ref,json=diagnosticRef,proto3" json:"diagnostic_ref,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnostic) Reset() {
	*x = Diagnostic{}
	mi := &file_runtime_v1_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostic) ProtoMessage() {}

func (x *Diagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostic.ProtoReflect.Descriptor instead.
func (*Diagnostic) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{17}
}

func (x *Diagnostic) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Diagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Diagnostic) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *Diagnostic) GetDiagnosticRef() string {
	if x != nil {
		return x.DiagnosticRef
	}
	return ""
}

type Terminal struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           TerminalStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=agenticstream.runtime.v1.TerminalStatus" json:"status,omitempty"`
	ReasonCode       string                 `protobuf:"bytes,2,opt,name=reason_code,json=reasonCode,proto3" json:"reason_code,omitempty"`
	DiagnosticRef    string                 `protobuf:"bytes,3,opt,name=diagnostic_ref,json=diagnosticRef,proto3" json:"diagnostic_ref,omitempty"`
	Usage            *Usage                 `protobuf:"bytes,4,opt,name=usage,proto3" json:"usage,omitempty"`
	ArtifactManifest *ArtifactManifest      `protobuf:"bytes,5,opt,name=artifact_manifest,json=artifactManifest,proto3" json:"artifact_manifest,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Terminal) Reset() {
	*x = Terminal{}
	mi := &file_runtime_v1_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Terminal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Terminal) ProtoMessage() {}

func (x *Terminal) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Terminal.ProtoReflect.Descriptor instead.
func (*Terminal) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{18}
}

func (x *Terminal) GetStatus() TerminalStatus {
	if x != nil {
		return x.Status
	}
	return TerminalStatus_TERMINAL_STATUS_UNSPECIFIED
}

func (x *Terminal) GetReasonCode() string {
	if x != nil {
		return x.ReasonCode
	}
	return ""
}

func (x *Terminal) GetDiagnosticRef() string {
	if x != nil {
		return x.DiagnosticRef
	}
	return ""
}

func (x *Terminal) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

func (x *Terminal) GetArtifactManifest() *ArtifactManifest {
	if x != nil {
		return x.ArtifactManifest
	}
	return nil
}

type ArtifactManifest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PromptSha256       []byte                 `protobuf:"bytes,1,opt,name=prompt_sha256,json=promptSha256,proto3" json:"prompt_sha256,omitempty"`
	SkillSetSha256     []byte                 `protobuf:"bytes,2,opt,name=skill_set_sha256,json=skillSetSha256,proto3" json:"skill_set_sha256,omitempty"`
	ToolCatalogSha256  []byte                 `protobuf:"bytes,3,opt,name=tool_catalog_sha256,json=toolCatalogSha256,proto3" json:"tool_catalog_sha256,omitempty"`
	ModelPolicy        string                 `protobuf:"bytes,4,opt,name=model_policy,json=modelPolicy,proto3" json:"model_policy,omitempty"`
	ContractVersion    string                 `protobuf:"bytes,5,opt,name=contract_version,json=contractVersion,proto3" json:"contract_version,omitempty"`
	MemoryRecordSha256 [][]byte               `protobuf:"bytes,6,rep,name=memory_record_sha256,json=memoryRecordSha256,proto3" json:"memory_record_sha256,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ArtifactManifest) Reset() {
	*x = ArtifactManifest{}
	mi := &file_runtime_v1_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactManifest) ProtoMessage() {}

func (x *ArtifactManifest) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactManifest.ProtoReflect.Descriptor instead.
func (*ArtifactManifest) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{19}
}

func (x *ArtifactManifest) GetPromptSha256() []byte {
	if x != nil {
		return x.PromptSha256
	}
	return nil
}

func (x *ArtifactManifest) GetSkillSetSha256() []byte {
	if x != nil {
		return x.SkillSetSha256
	}
	return nil
}

func (x *ArtifactManifest) GetToolCatalogSha256() []byte {
	if x != nil {
		return x.ToolCatalogSha256
	}
	return nil
}

func (x *ArtifactManifest) GetModelPolicy() string {
	if x != nil {
		return x.ModelPolicy
	}
	return ""
}

func (x *ArtifactManifest) GetContractVersion() string {
	if x != nil {
		return x.ContractVersion
	}
	return ""
}

func (x *ArtifactManifest) GetMemoryRecordSha256() [][]byte {
	if x != nil {
		return x.MemoryRecordSha256
	}
	return nil
}

type EvidenceToolCall struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	EpisodeId       string                 `protobuf:"bytes,2,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	CallId          string                 `protobuf:"bytes,3,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	ToolName        string                 `protobuf:"bytes,4,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ArgumentsJson   []byte                 `protobuf:"bytes,5,opt,name=arguments_json,json=argumentsJson,proto3" json:"arguments_json,omitempty"`
	CapabilityToken []byte                 `protobuf:"bytes,6,opt,name=capability_token,json=capabilityToken,proto3" json:"capability_token,omitempty"`
	Deadline        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=deadline,proto3" json:"deadline,omitempty"`
	AttemptId       string                 `protobuf:"bytes,8,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Fence           uint64                 `protobuf:"varint,9,opt,name=fence,proto3" json:"fence,omitempty"`
	Traceparent     string                 `protobuf:"bytes,10,opt,name=traceparent,proto3" json:"traceparent,omitempty"`
	Tracestate      string                 `protobuf:"bytes,11,opt,name=tracestate,proto3" json:"tracestate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EvidenceToolCall) Reset() {
	*x = EvidenceToolCall{}
	mi := &file_runtime_v1_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceToolCall) ProtoMessage() {}

func (x *EvidenceToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceToolCall.ProtoReflect.Descriptor instead.
func (*EvidenceToolCall) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{20}
}

func (x *EvidenceToolCall) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *EvidenceToolCall) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

func (x *EvidenceToolCall) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *EvidenceToolCall) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *EvidenceToolCall) GetArgumentsJson() []byte {
	if x != nil {
		return x.ArgumentsJson
	}
	return nil
}

func (x *EvidenceToolCall) GetCapabilityToken() []byte {
	if x != nil {
		return x.CapabilityToken
	}
	return nil
}

func (x *EvidenceToolCall) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

func (x *EvidenceToolCall) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *EvidenceToolCall) GetFence() uint64 {
	if x != nil {
		return x.Fence
	}
	return 0
}

func (x *EvidenceToolCall) GetTraceparent() string {
	if x != nil {
		return x.Traceparent
	}
	return ""
}

func (x *EvidenceToolCall) GetTracestate() string {
	if x != nil {
		return x.Tracestate
	}
	return ""
}

type EvidenceToolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EpisodeId     string                 `protobuf:"bytes,1,opt,name=episode_id,json=episodeId,proto3" json:"episode_id,omitempty"`
	CallId        string                 `protobuf:"bytes,2,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	IsError       bool                   `protobuf:"varint,3,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ResultJson    []byte                 `protobuf:"bytes,5,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	ResultSha256  []byte                 `protobuf:"bytes,6,opt,name=result_sha256,json=resultSha256,proto3" json:"result_sha256,omitempty"`
	Artifact      *ArtifactRef           `protobuf:"bytes,7,opt,name=artifact,proto3" json:"artifact,omitempty"`
	Truncated     bool                   `protobuf:"varint,8,opt,name=truncated,proto3" json:"truncated,omitempty"`
	AttemptId     string                 `protobuf:"bytes,9,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	Fence         uint64                 `protobuf:"varint,10,opt,name=fence,proto3" json:"fence,omitempty"`
	Traceparent   string                 `protobuf:"bytes,11,opt,name=traceparent,proto3" json:"traceparent,omitempty"`
	Tracestate    string                 `protobuf:"bytes,12,opt,name=tracestate,proto3" json:"tracestate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvidenceToolResult) Reset() {
	*x = EvidenceToolResult{}
	mi := &file_runtime_v1_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidenceToolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidenceToolResult) ProtoMessage() {}

func (x *EvidenceToolResult) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidenceToolResult.ProtoReflect.Descriptor instead.
func (*EvidenceToolResult) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{21}
}

func (x *EvidenceToolResult) GetEpisodeId() string {
	if x != nil {
		return x.EpisodeId
	}
	return ""
}

func (x *EvidenceToolResult) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *EvidenceToolResult) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

func (x *EvidenceToolResult) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *EvidenceToolResult) GetResultJson() []byte {
	if x != nil {
		return x.ResultJson
	}
	return nil
}

func (x *EvidenceToolResult) GetResultSha256() []byte {
	if x != nil {
		return x.ResultSha256
	}
	return nil
}

func (x *EvidenceToolResult) GetArtifact() *ArtifactRef {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *EvidenceToolResult) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *EvidenceToolResult) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

func (x *EvidenceToolResult) GetFence() uint64 {
	if x != nil {
		return x.Fence
	}
	return 0
}

func (x *EvidenceToolResult) GetTraceparent() string {
	if x != nil {
		return x.Traceparent
	}
	return ""
}

func (x *EvidenceToolResult) GetTracestate() string {
	if x != nil {
		return x.Tracestate
	}
	return ""
}

type ArtifactRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MediaType     string                 `protobuf:"bytes,2,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
	SizeBytes     uint64                 `protobuf:"varint,3,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Sha256        []byte                 `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactRef) Reset() {
	*x = ArtifactRef{}
	mi := &file_runtime_v1_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRef) ProtoMessage() {}

func (x *ArtifactRef) ProtoReflect() protoreflect.Message {
	mi := &file_runtime_v1_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactRef.ProtoReflect.Descriptor instead.
func (*ArtifactRef) Descriptor() ([]byte, []int) {
	return file_runtime_v1_proto_rawDescGZIP(), []int{22}
}

func (x *ArtifactRef) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ArtifactRef) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

func (x *ArtifactRef) GetSizeBytes() uint64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ArtifactRef) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

var File_runtime_v1_proto protoreflect.FileDescriptor

const file_runtime_v1_proto_rawDesc = "" +
	"\n" +
	"\x10runtime-v1.proto\x12\x18agenticstream.runtime.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfa\x03\n" +
	"\x10HandshakeRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12)\n" +
	"\x10contract_version\x18\x02 \x01(\tR\x0fcontractVersion\x12\x1b\n" +
	"\tworker_id\x18\x03 \x01(\tR\bworkerId\x12'\n" +
	"\x0fnon_interactive\x18\x04 \x01(\bR\x0enonInteractive\x12%\n" +
	"\x0eshadow_capable\x18\x05 \x01(\bR\rshadowCapable\x125\n" +
	"\x16counterfactual_capable\x18\x06 \x01(\bR\x15counterfactualCapable\x12?\n" +
	"\x1cemits_complete_replay_ledger\x18\a \x01(\bR\x19emitsCompleteReplayLedger\x12L\n" +
	"\x0esupports_kinds\x18\b \x03(\x0e2%.agenticstream.runtime.v1.EpisodeKindR\rsupportsKinds\x12.\n" +
	"\x13runtime_instance_id\x18\t \x01(\tR\x11runtimeInstanceId\x12-\n" +
	"\x12requested_features\x18\n" +
	" \x03(\tR\x11requestedFeatures\"\xb4\x02\n" +
	"\x11HandshakeResponse\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12)\n" +
	"\x10contract_version\x18\x02 \x01(\tR\x0fcontractVersion\x12\x1f\n" +
	"\vworker_name\x18\x03 \x01(\tR\n" +
	"workerName\x12%\n" +
	"\x0eworker_version\x18\x04 \x01(\tR\rworkerVersion\x12-\n" +
	"\x12supported_features\x18\x05 \x03(\tR\x11supportedFeatures\x12*\n" +
	"\x11max_request_bytes\x18\x06 \x01(\x04R\x0fmaxRequestBytes\x12&\n" +
	"\x0fmax_event_bytes\x18\a \x01(\x04R\rmaxEventBytes\"\x9c\f\n" +
	"\x0eEpisodeRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x02 \x01(\tR\tepisodeId\x12\x1d\n" +
	"\n" +
	"trigger_id\x18\x03 \x01(\tR\ttriggerId\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12!\n" +
	"\fsituation_id\x18\x05 \x01(\tR\vsituationId\x12+\n" +
	"\x11situation_version\x18\x06 \x01(\x04R\x10situationVersion\x12#\n" +
	"\rsnapshot_json\x18\n" +
	" \x01(\fR\fsnapshotJson\x12'\n" +
	"\x0fsnapshot_sha256\x18\v \x01(\fR\x0esnapshotSha256\x120\n" +
	"\x14decision_schema_json\x18\f \x01(\fR\x12decisionSchemaJson\x124\n" +
	"\x16decision_schema_sha256\x18\r \x01(\fR\x14decisionSchemaSha256\x12*\n" +
	"\x11tool_catalog_json\x18\x0e \x01(\fR\x0ftoolCatalogJson\x12.\n" +
	"\x13tool_catalog_sha256\x18\x0f \x01(\fR\x11toolCatalogSha256\x12\x1f\n" +
	"\vspec_sha256\x18\x10 \x01(\fR\n" +
	"specSha256\x12\x1c\n" +
	"\tobjective\x18\x14 \x01(\tR\tobjective\x12#\n" +
	"\rexecutor_name\x18\x15 \x01(\tR\fexecutorName\x12)\n" +
	"\x10executor_version\x18\x16 \x01(\tR\x0fexecutorVersion\x12!\n" +
	"\fmodel_policy\x18\x17 \x01(\tR\vmodelPolicy\x12%\n" +
	"\x0eprompt_version\x18\x18 \x01(\tR\rpromptVersion\x12?\n" +
	"\x06budget\x18\x1e \x01(\v2'.agenticstream.runtime.v1.EpisodeBudgetR\x06budget\x126\n" +
	"\bdeadline\x18\x1f \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12)\n" +
	"\x10supersession_key\x18  \x01(\tR\x0fsupersessionKey\x12 \n" +
	"\vtraceparent\x18! \x01(\tR\vtraceparent\x12\x1e\n" +
	"\n" +
	"tracestate\x18\" \x01(\tR\n" +
	"tracestate\x126\n" +
	"\x17evidence_tools_endpoint\x18( \x01(\tR\x15evidenceToolsEndpoint\x12)\n" +
	"\x10capability_token\x18) \x01(\fR\x0fcapabilityToken\x129\n" +
	"\x04kind\x182 \x01(\x0e2%.agenticstream.runtime.v1.EpisodeKindR\x04kind\x129\n" +
	"\x04lane\x183 \x01(\x0e2%.agenticstream.runtime.v1.EpisodeLaneR\x04lane\x12F\n" +
	"\frisk_ceiling\x184 \x01(\x0e2#.agenticstream.runtime.v1.RiskClassR\vriskCeiling\x120\n" +
	"\x14allowed_intent_types\x185 \x03(\tR\x12allowedIntentTypes\x12)\n" +
	"\x10cancellation_key\x186 \x01(\tR\x0fcancellationKey\x12\x1d\n" +
	"\n" +
	"attempt_id\x187 \x01(\tR\tattemptId\x12\x14\n" +
	"\x05fence\x188 \x01(\x04R\x05fence\x12[\n" +
	"\x13evidence_time_range\x189 \x01(\v2+.agenticstream.runtime.v1.EvidenceTimeRangeR\x11evidenceTimeRange\x12S\n" +
	"\x0freconsideration\x18: \x01(\v2).agenticstream.runtime.v1.ReconsiderationR\x0freconsideration\"u\n" +
	"\x11EvidenceTimeRange\x12.\n" +
	"\x04from\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04from\x120\n" +
	"\x05until\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05until\"\xd2\x01\n" +
	"\x0fReconsideration\x12.\n" +
	"\x13prior_decision_json\x18\x01 \x01(\fR\x11priorDecisionJson\x122\n" +
	"\x15executed_command_json\x18\x02 \x03(\fR\x13executedCommandJson\x122\n" +
	"\x15observed_outcome_json\x18\x03 \x03(\fR\x13observedOutcomeJson\x12'\n" +
	"\x0fcorrection_json\x18\x04 \x01(\fR\x0ecorrectionJson\"\xbe\x03\n" +
	"\rEpisodeBudget\x126\n" +
	"\twall_time\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\bwallTime\x12&\n" +
	"\x0fmax_model_calls\x18\x02 \x01(\rR\rmaxModelCalls\x12(\n" +
	"\x10max_input_tokens\x18\x03 \x01(\x04R\x0emaxInputTokens\x12*\n" +
	"\x11max_output_tokens\x18\x04 \x01(\x04R\x0fmaxOutputTokens\x12$\n" +
	"\x0emax_tool_calls\x18\x05 \x01(\rR\fmaxToolCalls\x121\n" +
	"\x15max_tool_result_bytes\x18\x06 \x01(\x04R\x12maxToolResultBytes\x12<\n" +
	"\x1bmax_total_tool_result_bytes\x18\a \x01(\x04R\x17maxTotalToolResultBytes\x120\n" +
	"\x14max_provider_retries\x18\b \x01(\rR\x12maxProviderRetries\x12.\n" +
	"\x13max_cost_microunits\x18\t \x01(\x04R\x11maxCostMicrounits\"\xed\a\n" +
	"\fEpisodeEvent\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x01 \x01(\tR\tepisodeId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12;\n" +
	"\voccurred_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x04 \x01(\tR\tattemptId\x12\x14\n" +
	"\x05fence\x18\x05 \x01(\x04R\x05fence\x12D\n" +
	"\astarted\x18\n" +
	" \x01(\v2(.agenticstream.runtime.v1.EpisodeStartedH\x00R\astarted\x12M\n" +
	"\rmodel_started\x18\v \x01(\v2&.agenticstream.runtime.v1.ModelStartedH\x00R\fmodelStarted\x12G\n" +
	"\vmodel_delta\x18\f \x01(\v2$.agenticstream.runtime.v1.ModelDeltaH\x00R\n" +
	"modelDelta\x12S\n" +
	"\x0fmodel_completed\x18\r \x01(\v2(.agenticstream.runtime.v1.ModelCompletedH\x00R\x0emodelCompleted\x12=\n" +
	"\x04tool\x18\x0e \x01(\v2'.agenticstream.runtime.v1.ToolLifecycleH\x00R\x04tool\x12M\n" +
	"\rtool_progress\x18\x14 \x01(\v2&.agenticstream.runtime.v1.ToolProgressH\x00R\ftoolProgress\x12A\n" +
	"\x06budget\x18\x0f \x01(\v2'.agenticstream.runtime.v1.BudgetUpdatedH\x00R\x06budget\x12H\n" +
	"\bdecision\x18\x10 \x01(\v2*.agenticstream.runtime.v1.DecisionProposedH\x00R\bdecision\x12F\n" +
	"\n" +
	"diagnostic\x18\x11 \x01(\v2$.agenticstream.runtime.v1.DiagnosticH\x00R\n" +
	"diagnostic\x12@\n" +
	"\bterminal\x18\x12 \x01(\v2\".agenticstream.runtime.v1.TerminalH\x00R\bterminal\x12M\n" +
	"\n" +
	"cancelling\x18\x13 \x01(\v2+.agenticstream.runtime.v1.EpisodeCancellingH\x00R\n" +
	"cancellingB\t\n" +
	"\apayload\"\x9a\x01\n" +
	"\x0eEpisodeStarted\x12\x1f\n" +
	"\vworker_name\x18\x01 \x01(\tR\n" +
	"workerName\x12%\n" +
	"\x0eworker_version\x18\x02 \x01(\tR\rworkerVersion\x12%\n" +
	"\x0emodel_provider\x18\x03 \x01(\tR\rmodelProvider\x12\x19\n" +
	"\bmodel_id\x18\x04 \x01(\tR\amodelId\"\x86\x01\n" +
	"\fModelStarted\x12\x18\n" +
	"\aordinal\x18\x01 \x01(\rR\aordinal\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x19\n" +
	"\bmodel_id\x18\x03 \x01(\tR\amodelId\x12%\n" +
	"\x0erequest_sha256\x18\x04 \x01(\fR\rrequestSha256\"~\n" +
	"\n" +
	"ModelDelta\x12#\n" +
	"\rmodel_ordinal\x18\x01 \x01(\rR\fmodelOrdinal\x127\n" +
	"\x04lane\x18\x02 \x01(\x0e2#.agenticstream.runtime.v1.DeltaLaneR\x04lane\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"\xaf\x01\n" +
	"\x0eModelCompleted\x12\x18\n" +
	"\aordinal\x18\x01 \x01(\rR\aordinal\x12#\n" +
	"\rfinish_reason\x18\x02 \x01(\tR\ffinishReason\x125\n" +
	"\x05usage\x18\x03 \x01(\v2\x1f.agenticstream.runtime.v1.UsageR\x05usage\x12'\n" +
	"\x0fresponse_sha256\x18\x04 \x01(\fR\x0eresponseSha256\"\xb7\x02\n" +
	"\rToolLifecycle\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x129\n" +
	"\x05state\x18\x03 \x01(\x0e2#.agenticstream.runtime.v1.ToolStateR\x05state\x12)\n" +
	"\x10arguments_sha256\x18\x04 \x01(\fR\x0fargumentsSha256\x12#\n" +
	"\rresult_sha256\x18\x05 \x01(\fR\fresultSha256\x12\x19\n" +
	"\bis_error\x18\x06 \x01(\bR\aisError\x12+\n" +
	"\x11execution_started\x18\a \x01(\bR\x10executionStarted\x12\x1d\n" +
	"\n" +
	"error_code\x18\b \x01(\tR\terrorCode\"c\n" +
	"\fToolProgress\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1d\n" +
	"\n" +
	"bytes_read\x18\x02 \x01(\x04R\tbytesRead\x12\x1b\n" +
	"\trows_read\x18\x03 \x01(\x04R\browsRead\"\xd3\x01\n" +
	"\x05Usage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x04R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x04R\foutputTokens\x12.\n" +
	"\x13cached_input_tokens\x18\x03 \x01(\x04R\x11cachedInputTokens\x12)\n" +
	"\x10reasoning_tokens\x18\x04 \x01(\x04R\x0freasoningTokens\x12'\n" +
	"\x0fcost_microunits\x18\x05 \x01(\x04R\x0ecostMicrounits\"\xa9\x02\n" +
	"\rBudgetUpdated\x12E\n" +
	"\tremaining\x18\x01 \x01(\v2'.agenticstream.runtime.v1.EpisodeBudgetR\tremaining\x12J\n" +
	"\x10cumulative_usage\x18\x02 \x01(\v2\x1f.agenticstream.runtime.v1.UsageR\x0fcumulativeUsage\x12(\n" +
	"\x10model_calls_used\x18\x03 \x01(\rR\x0emodelCallsUsed\x12&\n" +
	"\x0ftool_calls_used\x18\x04 \x01(\rR\rtoolCallsUsed\x123\n" +
	"\x16tool_result_bytes_used\x18\x05 \x01(\x04R\x13toolResultBytesUsed\"\xb4\x01\n" +
	"\x10DecisionProposed\x12#\n" +
	"\rdecision_json\x18\x01 \x01(\fR\fdecisionJson\x12'\n" +
	"\x0fdecision_sha256\x18\x02 \x01(\fR\x0edecisionSha256\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x03 \x01(\tR\tepisodeId\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x04 \x01(\tR\tattemptId\x12\x14\n" +
	"\x05fence\x18\x05 \x01(\x04R\x05fence\"l\n" +
	"\x11EpisodeCancelling\x12\x1f\n" +
	"\vreason_code\x18\x01 \x01(\tR\n" +
	"reasonCode\x126\n" +
	"\bdeadline\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"\x7f\n" +
	"\n" +
	"Diagnostic\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x12%\n" +
	"\x0ediagnostic_ref\x18\x04 \x01(\tR\rdiagnosticRef\"\xa4\x02\n" +
	"\bTerminal\x12@\n" +
	"\x06status\x18\x01 \x01(\x0e2(.agenticstream.runtime.v1.TerminalStatusR\x06status\x12\x1f\n" +
	"\vreason_code\x18\x02 \x01(\tR\n" +
	"reasonCode\x12%\n" +
	"\x0ediagnostic_ref\x18\x03 \x01(\tR\rdiagnosticRef\x125\n" +
	"\x05usage\x18\x04 \x01(\v2\x1f.agenticstream.runtime.v1.UsageR\x05usage\x12W\n" +
	"\x11artifact_manifest\x18\x05 \x01(\v2*.agenticstream.runtime.v1.ArtifactManifestR\x10artifactManifest\"\x91\x02\n" +
	"\x10ArtifactManifest\x12#\n" +
	"\rprompt_sha256\x18\x01 \x01(\fR\fpromptSha256\x12(\n" +
	"\x10skill_set_sha256\x18\x02 \x01(\fR\x0eskillSetSha256\x12.\n" +
	"\x13tool_catalog_sha256\x18\x03 \x01(\fR\x11toolCatalogSha256\x12!\n" +
	"\fmodel_policy\x18\x04 \x01(\tR\vmodelPolicy\x12)\n" +
	"\x10contract_version\x18\x05 \x01(\tR\x0fcontractVersion\x120\n" +
	"\x14memory_record_sha256\x18\x06 \x03(\fR\x12memoryRecordSha256\"\x93\x03\n" +
	"\x10EvidenceToolCall\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x02 \x01(\tR\tepisodeId\x12\x17\n" +
	"\acall_id\x18\x03 \x01(\tR\x06callId\x12\x1b\n" +
	"\ttool_name\x18\x04 \x01(\tR\btoolName\x12%\n" +
	"\x0earguments_json\x18\x05 \x01(\fR\rargumentsJson\x12)\n" +
	"\x10capability_token\x18\x06 \x01(\fR\x0fcapabilityToken\x126\n" +
	"\bdeadline\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\b \x01(\tR\tattemptId\x12\x14\n" +
	"\x05fence\x18\t \x01(\x04R\x05fence\x12 \n" +
	"\vtraceparent\x18\n" +
	" \x01(\tR\vtraceparent\x12\x1e\n" +
	"\n" +
	"tracestate\x18\v \x01(\tR\n" +
	"tracestate\"\xa4\x03\n" +
	"\x12EvidenceToolResult\x12\x1d\n" +
	"\n" +
	"episode_id\x18\x01 \x01(\tR\tepisodeId\x12\x17\n" +
	"\acall_id\x18\x02 \x01(\tR\x06callId\x12\x19\n" +
	"\bis_error\x18\x03 \x01(\bR\aisError\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12\x1f\n" +
	"\vresult_json\x18\x05 \x01(\fR\n" +
	"resultJson\x12#\n" +
	"\rresult_sha256\x18\x06 \x01(\fR\fresultSha256\x12A\n" +
	"\bartifact\x18\a \x01(\v2%.agenticstream.runtime.v1.ArtifactRefR\bartifact\x12\x1c\n" +
	"\ttruncated\x18\b \x01(\bR\ttruncated\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\t \x01(\tR\tattemptId\x12\x14\n" +
	"\x05fence\x18\n" +
	" \x01(\x04R\x05fence\x12 \n" +
	"\vtraceparent\x18\v \x01(\tR\vtraceparent\x12\x1e\n" +
	"\n" +
	"tracestate\x18\f \x01(\tR\n" +
	"tracestate\"s\n" +
	"\vArtifactRef\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"media_type\x18\x02 \x01(\tR\tmediaType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x03 \x01(\x04R\tsizeBytes\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\fR\x06sha256*c\n" +
	"\vEpisodeKind\x12\x1c\n" +
	"\x18EPISODE_KIND_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15EPISODE_KIND_DIAGNOSE\x10\x01\x12\x1b\n" +
	"\x17EPISODE_KIND_RECONSIDER\x10\x02*q\n" +
	"\vEpisodeLane\x12\x1c\n" +
	"\x18EPISODE_LANE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EPISODE_LANE_FAST\x10\x01\x12\x15\n" +
	"\x11EPISODE_LANE_DEEP\x10\x02\x12\x16\n" +
	"\x12EPISODE_LANE_BATCH\x10\x03*\x86\x01\n" +
	"\tRiskClass\x12\x1a\n" +
	"\x16RISK_CLASS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rRISK_CLASS_R0\x10\x01\x12\x11\n" +
	"\rRISK_CLASS_R1\x10\x02\x12\x11\n" +
	"\rRISK_CLASS_R2\x10\x03\x12\x11\n" +
	"\rRISK_CLASS_R3\x10\x04\x12\x11\n" +
	"\rRISK_CLASS_R4\x10\x05*\\\n" +
	"\tDeltaLane\x12\x1a\n" +
	"\x16DELTA_LANE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14DELTA_LANE_ASSISTANT\x10\x01\x12\x19\n" +
	"\x15DELTA_LANE_COMMENTARY\x10\x02*\x8b\x01\n" +
	"\tToolState\x12\x1a\n" +
	"\x16TOOL_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14TOOL_STATE_REQUESTED\x10\x01\x12\x16\n" +
	"\x12TOOL_STATE_STARTED\x10\x02\x12\x18\n" +
	"\x14TOOL_STATE_COMPLETED\x10\x03\x12\x16\n" +
	"\x12TOOL_STATE_BLOCKED\x10\x04*\xed\x01\n" +
	"\x0eTerminalStatus\x12\x1f\n" +
	"\x1bTERMINAL_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18TERMINAL_STATUS_PRODUCED\x10\x01\x12\x1c\n" +
	"\x18TERMINAL_STATUS_DECLINED\x10\x02\x12\x1d\n" +
	"\x19TERMINAL_STATUS_CANCELLED\x10\x03\x12\x1a\n" +
	"\x16TERMINAL_STATUS_FAILED\x10\x04\x12\x1d\n" +
	"\x19TERMINAL_STATUS_TIMED_OUT\x10\x05\x12$\n" +
	" TERMINAL_STATUS_BUDGET_EXHAUSTED\x10\x062\xd4\x01\n" +
	"\rEpisodeWorker\x12d\n" +
	"\tHandshake\x12*.agenticstream.runtime.v1.HandshakeRequest\x1a+.agenticstream.runtime.v1.HandshakeResponse\x12]\n" +
	"\aExecute\x12(.agenticstream.runtime.v1.EpisodeRequest\x1a&.agenticstream.runtime.v1.EpisodeEvent0\x012q\n" +
	"\rEvidenceTools\x12`\n" +
	"\x04Call\x12*.agenticstream.runtime.v1.EvidenceToolCall\x1a,.agenticstream.runtime.v1.EvidenceToolResultBXZVgithub.com/ghassan-ai-projects/agentic-stream/proto/agenticstream/runtime/v1;runtimev1b\x06proto3"

var (
	file_runtime_v1_proto_rawDescOnce sync.Once
	file_runtime_v1_proto_rawDescData []byte
)

func file_runtime_v1_proto_rawDescGZIP() []byte {
	file_runtime_v1_proto_rawDescOnce.Do(func() {
		file_runtime_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_runtime_v1_proto_rawDesc), len(file_runtime_v1_proto_rawDesc)))
	})
	return file_runtime_v1_proto_rawDescData
}

var file_runtime_v1_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_runtime_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_runtime_v1_proto_goTypes = []any{
	(EpisodeKind)(0),              // 0: agenticstream.runtime.v1.EpisodeKind
	(EpisodeLane)(0),              // 1: agenticstream.runtime.v1.EpisodeLane
	(RiskClass)(0),                // 2: agenticstream.runtime.v1.RiskClass
	(DeltaLane)(0),                // 3: agenticstream.runtime.v1.DeltaLane
	(ToolState)(0),                // 4: agenticstream.runtime.v1.ToolState
	(TerminalStatus)(0),           // 5: agenticstream.runtime.v1.TerminalStatus
	(*HandshakeRequest)(nil),      // 6: agenticstream.runtime.v1.HandshakeRequest
	(*HandshakeResponse)(nil),     // 7: agenticstream.runtime.v1.HandshakeResponse
	(*EpisodeRequest)(nil),        // 8: agenticstream.runtime.v1.EpisodeRequest
	(*EvidenceTimeRange)(nil),     // 9: agenticstream.runtime.v1.EvidenceTimeRange
	(*Reconsideration)(nil),       // 10: agenticstream.runtime.v1.Reconsideration
	(*EpisodeBudget)(nil),         // 11: agenticstream.runtime.v1.EpisodeBudget
	(*EpisodeEvent)(nil),          // 12: agenticstream.runtime.v1.EpisodeEvent
	(*EpisodeStarted)(nil),        // 13: agenticstream.runtime.v1.EpisodeStarted
	(*ModelStarted)(nil),          // 14: agenticstream.runtime.v1.ModelStarted
	(*ModelDelta)(nil),            // 15: agenticstream.runtime.v1.ModelDelta
	(*ModelCompleted)(nil),        // 16: agenticstream.runtime.v1.ModelCompleted
	(*ToolLifecycle)(nil),         // 17: agenticstream.runtime.v1.ToolLifecycle
	(*ToolProgress)(nil),          // 18: agenticstream.runtime.v1.ToolProgress
	(*Usage)(nil),                 // 19: agenticstream.runtime.v1.Usage
	(*BudgetUpdated)(nil),         // 20: agenticstream.runtime.v1.BudgetUpdated
	(*DecisionProposed)(nil),      // 21: agenticstream.runtime.v1.DecisionProposed
	(*EpisodeCancelling)(nil),     // 22: agenticstream.runtime.v1.EpisodeCancelling
	(*Diagnostic)(nil),            // 23: agenticstream.runtime.v1.Diagnostic
	(*Terminal)(nil),              // 24: agenticstream.runtime.v1.Terminal
	(*ArtifactManifest)(nil),      // 25: agenticstream.runtime.v1.ArtifactManifest
	(*EvidenceToolCall)(nil),      // 26: agenticstream.runtime.v1.EvidenceToolCall
	(*EvidenceToolResult)(nil),    // 27: agenticstream.runtime.v1.EvidenceToolResult
	(*ArtifactRef)(nil),           // 28: agenticstream.runtime.v1.ArtifactRef
	(*timestamppb.Timestamp)(nil), // 29: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 30: google.protobuf.Duration
}
var file_runtime_v1_proto_depIdxs = []int32{
	0,  // 0: agenticstream.runtime.v1.HandshakeRequest.supports_kinds:type_name -> agenticstream.runtime.v1.EpisodeKind
	11, // 1: agenticstream.runtime.v1.EpisodeRequest.budget:type_name -> agenticstream.runtime.v1.EpisodeBudget
	29, // 2: agenticstream.runtime.v1.EpisodeRequest.deadline:type_name -> google.protobuf.Timestamp
	0,  // 3: agenticstream.runtime.v1.EpisodeRequest.kind:type_name -> agenticstream.runtime.v1.EpisodeKind
	1,  // 4: agenticstream.runtime.v1.EpisodeRequest.lane:type_name -> agenticstream.runtime.v1.EpisodeLane
	2,  // 5: agenticstream.runtime.v1.EpisodeRequest.risk_ceiling:type_name -> agenticstream.runtime.v1.RiskClass
	9,  // 6: agenticstream.runtime.v1.EpisodeRequest.evidence_time_range:type_name -> agenticstream.runtime.v1.EvidenceTimeRange
	10, // 7: agenticstream.runtime.v1.EpisodeRequest.reconsideration:type_name -> agenticstream.runtime.v1.Reconsideration
	29, // 8: agenticstream.runtime.v1.EvidenceTimeRange.from:type_name -> google.protobuf.Timestamp
	29, // 9: agenticstream.runtime.v1.EvidenceTimeRange.until:type_name -> google.protobuf.Timestamp
	30, // 10: agenticstream.runtime.v1.EpisodeBudget.wall_time:type_name -> google.protobuf.Duration
	29, // 11: agenticstream.runtime.v1.EpisodeEvent.occurred_at:type_name -> google.protobuf.Timestamp
	13, // 12: agenticstream.runtime.v1.EpisodeEvent.started:type_name -> agenticstream.runtime.v1.EpisodeStarted
	14, // 13: agenticstream.runtime.v1.EpisodeEvent.model_started:type_name -> agenticstream.runtime.v1.ModelStarted
	15, // 14: agenticstream.runtime.v1.EpisodeEvent.model_delta:type_name -> agenticstream.runtime.v1.ModelDelta
	16, // 15: agenticstream.runtime.v1.EpisodeEvent.model_completed:type_name -> agenticstream.runtime.v1.ModelCompleted
	17, // 16: agenticstream.runtime.v1.EpisodeEvent.tool:type_name -> agenticstream.runtime.v1.ToolLifecycle
	18, // 17: agenticstream.runtime.v1.EpisodeEvent.tool_progress:type_name -> agenticstream.runtime.v1.ToolProgress
	20, // 18: agenticstream.runtime.v1.EpisodeEvent.budget:type_name -> agenticstream.runtime.v1.BudgetUpdated
	21, // 19: agenticstream.runtime.v1.EpisodeEvent.decision:type_name -> agenticstream.runtime.v1.DecisionProposed
	23, // 20: agenticstream.runtime.v1.EpisodeEvent.diagnostic:type_name -> agenticstream.runtime.v1.Diagnostic
	24, // 21: agenticstream.runtime.v1.EpisodeEvent.terminal:type_name -> agenticstream.runtime.v1.Terminal
	22, // 22: agenticstream.runtime.v1.EpisodeEvent.cancelling:type_name -> agenticstream.runtime.v1.EpisodeCancelling
	3,  // 23: agenticstream.runtime.v1.ModelDelta.lane:type_name -> agenticstream.runtime.v1.DeltaLane
	19, // 24: agenticstream.runtime.v1.ModelCompleted.usage:type_name -> agenticstream.runtime.v1.Usage
	4,  // 25: agenticstream.runtime.v1.ToolLifecycle.state:type_name -> agenticstream.runtime.v1.ToolState
	11, // 26: agenticstream.runtime.v1.BudgetUpdated.remaining:type_name -> agenticstream.runtime.v1.EpisodeBudget
	19, // 27: agenticstream.runtime.v1.BudgetUpdated.cumulative_usage:type_name -> agenticstream.runtime.v1.Usage
	29, // 28: agenticstream.runtime.v1.EpisodeCancelling.deadline:type_name -> google.protobuf.Timestamp
	5,  // 29: agenticstream.runtime.v1.Terminal.status:type_name -> agenticstream.runtime.v1.TerminalStatus
	19, // 30: agenticstream.runtime.v1.Terminal.usage:type_name -> agenticstream.runtime.v1.Usage
	25, // 31: agenticstream.runtime.v1.Terminal.artifact_manifest:type_name -> agenticstream.runtime.v1.ArtifactManifest
	29, // 32: agenticstream.runtime.v1.EvidenceToolCall.deadline:type_name -> google.protobuf.Timestamp
	28, // 33: agenticstream.runtime.v1.EvidenceToolResult.artifact:type_name -> agenticstream.runtime.v1.ArtifactRef
	6,  // 34: agenticstream.runtime.v1.EpisodeWorker.Handshake:input_type -> agenticstream.runtime.v1.HandshakeRequest
	8,  // 35: agenticstream.runtime.v1.EpisodeWorker.Execute:input_type -> agenticstream.runtime.v1.EpisodeRequest
	26, // 36: agenticstream.runtime.v1.EvidenceTools.Call:input_type -> agenticstream.runtime.v1.EvidenceToolCall
	7,  // 37: agenticstream.runtime.v1.EpisodeWorker.Handshake:output_type -> agenticstream.runtime.v1.HandshakeResponse
	12, // 38: agenticstream.runtime.v1.EpisodeWorker.Execute:output_type -> agenticstream.runtime.v1.EpisodeEvent
	27, // 39: agenticstream.runtime.v1.EvidenceTools.Call:output_type -> agenticstream.runtime.v1.EvidenceToolResult
	37, // [37:40] is the sub-list for method output_type
	34, // [34:37] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_runtime_v1_proto_init() }
func file_runtime_v1_proto_init() {
	if File_runtime_v1_proto != nil {
		return
	}
	file_runtime_v1_proto_msgTypes[6].OneofWrappers = []any{
		(*EpisodeEvent_Started)(nil),
		(*EpisodeEvent_ModelStarted)(nil),
		(*EpisodeEvent_ModelDelta)(nil),
		(*EpisodeEvent_ModelCompleted)(nil),
		(*EpisodeEvent_Tool)(nil),
		(*EpisodeEvent_ToolProgress)(nil),
		(*EpisodeEvent_Budget)(nil),
		(*EpisodeEvent_Decision)(nil),
		(*EpisodeEvent_Diagnostic)(nil),
		(*EpisodeEvent_Terminal)(nil),
		(*EpisodeEvent_Cancelling)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_runtime_v1_proto_rawDesc), len(file_runtime_v1_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_runtime_v1_proto_goTypes,
		DependencyIndexes: file_runtime_v1_proto_depIdxs,
		EnumInfos:         file_runtime_v1_proto_enumTypes,
		MessageInfos:      file_runtime_v1_proto_msgTypes,
	}.Build()
	File_runtime_v1_proto = out.File
	file_runtime_v1_proto_goTypes = nil
	file_runtime_v1_proto_depIdxs = nil
}
