// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: runtime-v1.proto

package runtimev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EpisodeWorker_Handshake_FullMethodName = "/agenticstream.runtime.v1.EpisodeWorker/Handshake"
	EpisodeWorker_Execute_FullMethodName   = "/agenticstream.runtime.v1.EpisodeWorker/Execute"
)

// EpisodeWorkerClient is the client API for EpisodeWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EpisodeWorkerClient interface {
	// Verifies protocol compatibility and supported optional features.
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	// Executes one immutable, bounded episode. The final event must be Terminal.
	// Cancellation of the RPC is the primary cancellation mechanism.
	Execute(ctx context.Context, in *EpisodeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EpisodeEvent], error)
}

type episodeWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewEpisodeWorkerClient(cc grpc.ClientConnInterface) EpisodeWorkerClient {
	return &episodeWorkerClient{cc}
}

func (c *episodeWorkerClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, EpisodeWorker_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *episodeWorkerClient) Execute(ctx context.Context, in *EpisodeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EpisodeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EpisodeWorker_ServiceDesc.Streams[0], EpisodeWorker_Execute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EpisodeRequest, EpisodeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EpisodeWorker_ExecuteClient = grpc.ServerStreamingClient[EpisodeEvent]

// EpisodeWorkerServer is the server API for EpisodeWorker service.
// All implementations must embed UnimplementedEpisodeWorkerServer
// for forward compatibility.
type EpisodeWorkerServer interface {
	// Verifies protocol compatibility and supported optional features.
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	// Executes one immutable, bounded episode. The final event must be Terminal.
	// Cancellation of the RPC is the primary cancellation mechanism.
	Execute(*EpisodeRequest, grpc.ServerStreamingServer[EpisodeEvent]) error
	mustEmbedUnimplementedEpisodeWorkerServer()
}

// UnimplementedEpisodeWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEpisodeWorkerServer struct{}

func (UnimplementedEpisodeWorkerServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedEpisodeWorkerServer) Execute(*EpisodeRequest, grpc.ServerStreamingServer[EpisodeEvent]) error {
	return status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedEpisodeWorkerServer) mustEmbedUnimplementedEpisodeWorkerServer() {}
func (UnimplementedEpisodeWorkerServer) testEmbeddedByValue()                       {}

// UnsafeEpisodeWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EpisodeWorkerServer will
// result in compilation errors.
type UnsafeEpisodeWorkerServer interface {
	mustEmbedUnimplementedEpisodeWorkerServer()
}

func RegisterEpisodeWorkerServer(s grpc.ServiceRegistrar, srv EpisodeWorkerServer) {
	// If the following call panics, it indicates UnimplementedEpisodeWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EpisodeWorker_ServiceDesc, srv)
}

func _EpisodeWorker_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EpisodeWorkerServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EpisodeWorker_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EpisodeWorkerServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EpisodeWorker_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EpisodeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EpisodeWorkerServer).Execute(m, &grpc.GenericServerStream[EpisodeRequest, EpisodeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EpisodeWorker_ExecuteServer = grpc.ServerStreamingServer[EpisodeEvent]

// EpisodeWorker_ServiceDesc is the grpc.ServiceDesc for EpisodeWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EpisodeWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agenticstream.runtime.v1.EpisodeWorker",
	HandlerType: (*EpisodeWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _EpisodeWorker_Handshake_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Execute",
			Handler:       _EpisodeWorker_Execute_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "runtime-v1.proto",
}

const (
	EvidenceTools_Call_FullMethodName = "/agenticstream.runtime.v1.EvidenceTools/Call"
)

// EvidenceToolsClient is the client API for EvidenceTools service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Hosted by the Go runtime. A worker may call only the tools encoded in its
// short-lived capability token.
type EvidenceToolsClient interface {
	Call(ctx context.Context, in *EvidenceToolCall, opts ...grpc.CallOption) (*EvidenceToolResult, error)
}

type evidenceToolsClient struct {
	cc grpc.ClientConnInterface
}

func NewEvidenceToolsClient(cc grpc.ClientConnInterface) EvidenceToolsClient {
	return &evidenceToolsClient{cc}
}

func (c *evidenceToolsClient) Call(ctx context.Context, in *EvidenceToolCall, opts ...grpc.CallOption) (*EvidenceToolResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvidenceToolResult)
	err := c.cc.Invoke(ctx, EvidenceTools_Call_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EvidenceToolsServer is the server API for EvidenceTools service.
// All implementations must embed UnimplementedEvidenceToolsServer
// for forward compatibility.
//
// Hosted by the Go runtime. A worker may call only the tools encoded in its
// short-lived capability token.
type EvidenceToolsServer interface {
	Call(context.Context, *EvidenceToolCall) (*EvidenceToolResult, error)
	mustEmbedUnimplementedEvidenceToolsServer()
}

// UnimplementedEvidenceToolsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEvidenceToolsServer struct{}

func (UnimplementedEvidenceToolsServer) Call(context.Context, *EvidenceToolCall) (*EvidenceToolResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedEvidenceToolsServer) mustEmbedUnimplementedEvidenceToolsServer() {}
func (UnimplementedEvidenceToolsServer) testEmbeddedByValue()                       {}

// UnsafeEvidenceToolsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EvidenceToolsServer will
// result in compilation errors.
type UnsafeEvidenceToolsServer interface {
	mustEmbedUnimplementedEvidenceToolsServer()
}

func RegisterEvidenceToolsServer(s grpc.ServiceRegistrar, srv EvidenceToolsServer) {
	// If the following call panics, it indicates UnimplementedEvidenceToolsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EvidenceTools_ServiceDesc, srv)
}

func _EvidenceTools_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvidenceToolCall)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvidenceToolsServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EvidenceTools_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvidenceToolsServer).Call(ctx, req.(*EvidenceToolCall))
	}
	return interceptor(ctx, in, info, handler)
}

// EvidenceTools_ServiceDesc is the grpc.ServiceDesc for EvidenceTools service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EvidenceTools_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agenticstream.runtime.v1.EvidenceTools",
	HandlerType: (*EvidenceToolsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _EvidenceTools_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "runtime-v1.proto",
}
